### ISSUE TITLE
Move work item list to this repo

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#1]
Work items are currently listed in the github-pages landing page. Move them here and ensure they are up to date

**Comment by jandrieu** [comment]
DID & Method Specs (Manu Sporny)
Engagement Model (Joe Andrieu)
Data Minimization & Selective Disclosure (Lionel Wolberger)
Registries Process (need Spec-Text version) https://lists.w3.org/Archives/Public/public-credentials/2017Dec/0020.html
DID Method Registry http://bit.ly/2AHJ1KG
Linked Data Key Types Registry http://bit.ly/2jfhpZs
Credential Status Method Registry https://w3c-ccg.github.io/vc-status-registry/
Verifiable Claims Browser API and Browser Polyfill (Dave Longley)
Educational and Occupational Verifiable Credentials (Kim Duffy)

**Comment by msporny** [comment]
Don't forget:

* Object Capabilities for Linked Data (Chris Webber)

**Comment by kimdhamilton** [comment]
https://github.com/w3c-ccg/community/blob/master/work_items.md
