### ISSUE TITLE
Need Curated Guide to Implementations of CCG related specifications

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#104]
The CCG chairs have many, many tasks that we take care of for this community, but we can't take them all on, and we need help.

Though a lists of current specifications and methods will emerge in various registries, we need a curated list of implementations with the target audience being engineers coming to our community looking for code repositories of reference implementations, various code and platform implementations, etc.

I suggest that this can be a web page or so, linked to our home page at https://w3c-ccg.github.io/ and be hosted as a page in that repo https://github.com/w3c-ccg/w3c-ccg.github.io.

This would be a great first issue for someone to take on from in our community to tackle. It only involves creating a first draft of the document, and as initial version of this would probably take 4-8 hours to research and post and the volunteer would be done.

-- Christopher Allen

**Comment by kimdhamilton** [comment]
Closing as not actionable; this will need to be volunteer-driven
