### ISSUE TITLE
Ask Digital Bazaar to consider moving master did:key repo to CCG

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#107]
Action item from CCG meeting https://w3c-ccg.github.io/meetings/2020-03-03/ : 

From a request by @OR13 
"@dmitriz to ask DB to consider moving did:web to CCG"

**Comment by dmitrizagidulin** [comment]
@ChristopherA I think you meant `did:key` -- `did:web` is already in the CCG at https://github.com/w3c-ccg/did-method-web. Will work to xfer did:key though.

**Comment by dmitrizagidulin** [comment]
@ChristopherA - can you delete the current repo over at https://github.com/w3c-ccg/did-method-key ?
After that, we can transfer https://github.com/digitalbazaar/did-method-key repo over to the CCG.

**Comment by dmitrizagidulin** [comment]
(Although before deleting, we should probably transfer issue https://github.com/w3c-ccg/did-method-key/issues/1 to another repo, so that it's not lost in deletion.)

**Comment by OR13** [comment]
I copied an image of the thread there... https://github.com/digitalbazaar/did-method-key/issues/3

**Comment by OR13** [comment]
I have transferred the issue here: https://github.com/w3c-ccg/community/issues/110

**Comment by OR13** [comment]
@dmitrizagidulin I have deleted this repo, please transfer whenever possible.

**Comment by dmitrizagidulin** [comment]
@OR13 - excellent! And here we go, https://github.com/w3c-ccg/did-method-key is transferred!

**Comment by OR13** [comment]
I have transferred the orphan issued back, closing this issue.
