### ISSUE TITLE
Wrap up transition of DID Uses Cases now that it is DID-WG deliverable

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#108]
Action item from CCG meeting https://w3c-ccg.github.io/meetings/2020-03-03/ : 

"@joeandrieu will puzzle DID Use Cases how to wrap it"

**Comment by ChristopherA** [comment]
I think this is mostly putting some text in that repo and work item index that that this work item is complete and transitioned to a new repo in the DID-WG (links), that work is continuing there, and this marked this version archived in GitHub (so no new issues or PRs).

**Comment by jandrieu** [comment]
Ok. I updated the old repo. Work items was already updated. I archived the repo.

**Comment by OR13** [comment]
Seems like this needs to be linked to from the did core spec somehow... evidence of that would suffice IMO.

**Comment by jandrieu** [comment]
Haven't updated the did-core spec to point to the new URL.

1. Update the URL at the top of the ccg repo
2. Add a meta-redirect to new use cases document for the github.io

**Comment by kimdhamilton** [comment]
This has been addressed:
- did-core spec points to w3c did use case url
- ccg URL points to w3c did use case url

where w3c did use case URL = https://w3c.github.io/did-use-cases/
