### ISSUE TITLE
Close out DID Explainer work item

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#109]
Action item from CCG meeting https://w3c-ccg.github.io/meetings/2020-03-03/ :

"@burn & @JoeAndrieu to close out explainer work item"

**Comment by ChristopherA** [comment]
I think this is mostly putting some text in that repo and work item index that that this work item is closed and marked as archived in GitHub (so no new issues or PRs), that the DID-WG is formed (links), and that this work item is not being used by DID-WG and if any new DID Explainer for TAG is needed it will be created there.

**Comment by jandrieu** [comment]
@burnburn What do we need to do to close this? 

I believe this is firmly in the hands of the DID WG, so I **think** we can close this item and remove it from the list.

**Comment by ChristopherA** [comment]
What is the process for closing a work item list other than deleting it from the work item list? Do we delete the repo? Archive the repo? What do we do with DONE stuff that didn't get published.

**Comment by kimdhamilton** [comment]
Confirm we can hand over. This belongs to DID WG.

**Comment by burnburn** [comment]
Agreed this should be closed.  DID WG has it

**Comment by kimdhamilton** [comment]
Moved to "completed" section of work items. Closing.
