### ISSUE TITLE
Repo for VC Browser Polyfill?

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#11]
_From @kimdhamilton on August 2, 2017 0:22_

_Copied from original issue: w3c-ccg/w3c-ccg.github.io#5_

**Comment by kimdhamilton** [comment]
_From @msporny on August 2, 2017 0:44_

Spec-Ops is currently hosting that repo: https://github.com/Spec-Ops/credentials-polyfill ... and I know @dlongley is currently generalizing that framework to work for both Web Payments and Verifiable Claims here: https://github.com/digitalbazaar/web-request-mediator/tree/implementation ... so let's hold off on a repo until that work settles (which should happen by the end of September/October at the latest).

**Comment by kimdhamilton** [comment]
Sounds good; we'll wait

**Comment by dlongley** [comment]
Btw, the current location for the credential handler polyfill is here:

https://github.com/digitalbazaar/credential-handler-polyfill

**Comment by dlongley** [comment]
I should add there are additional parts required to make the whole polyfill work, but these are intended to be run on a single, community run website that implements the "credential mediator" piece.

The code for the site that performs this role in the demos we have is here:

https://github.com/digitalbazaar/authorization.io

It uses this code for the specific mediator parts called out in the Credential Handler API:

https://github.com/digitalbazaar/credential-mediator-polyfill

**Comment by dlongley** [comment]
And demo code for the whole thing is here:

https://github.com/digitalbazaar/credential-handler-demo

**Comment by kimdhamilton** [comment]
Closing this; we'll track separately
