### ISSUE TITLE
Discuss vc-examples

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#111]
# New Work Item Proposal: VC-examples

## Link to Abstract or Draft 

https://lists.w3.org/Archives/Public/public-credentials/2020Mar/0033.html

## Owners

@OR13  + need one more

**Comment by OR13** [comment]
Happy to discuss on the next call. trying to save the mailing list from spam.

**Comment by peacekeeper** [comment]
Great new work item, this will be very useful for the VC community.

**Comment by kimdhamilton** [comment]
Approved. Added to list
