### ISSUE TITLE
Review Registry Commitments & Update Work Items List

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#112]
We need to review our registry commitments and update our work items list.

Initially a chair's item, but maybe schedule a community discussion later.

-- Christopher Allen

**Comment by ChristopherA** [comment]
To review after elections.

**Comment by kimdhamilton** [comment]
Consolidating issues:

Action item from CCG meeting https://w3c-ccg.github.io/meetings/2020-03-03/ :

The leads for each of the CCG work items should be listed in the work items list https://w3c-ccg.github.io/community/work_items.html

We need a volunteer for this brief task. A good first issue for a new member of the CCG.

**Comment by kimdhamilton** [comment]
Tracking elsewhere
