### ISSUE TITLE
[PROPOSED WORK ITEM] lds-jws2020 code repository

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#113]
# New Work Item Proposal

I'd like to propose moving the [lds-jws2020](https://github.com/transmute-industries/lds-jws2020) code repo to the CCG and take it on as a CCG work item (ongoing community draft > reference code). There's interest from the VC-EDU task force in using this signature suite, and we'd like to continue iterating on it within the task force.

This allows us to use JSON-LD canonicalization while using standard/tested JOSE libraries for signing VCs.

## Link to Abstract or Draft 

https://github.com/transmute-industries/lds-jws2020

## List Owners

@OR13 @kimdhamilton

**Comment by ChristopherA** [comment]
Who are the proposed leads?

**Comment by ChristopherA** [comment]
+1 with two independent leads.

**Comment by OR13** [comment]
I'm happy to move the repo to the ccg, and update the ld crypto registry links accordingly.

**Comment by kimdhamilton** [comment]
ok to proceed

**Comment by OR13** [comment]
So next step is to to move the repo the CCG?

**Comment by OR13** [comment]
in progress

**Comment by OR13** [comment]
@kimdhamilton @ChristopherA I have moved the repo, and added what I think is required: https://github.com/w3c-ccg/lds-jws2020

Please create issues on the repo and assign me, if there are additional requirements to be made.

**Comment by OR13** [comment]
I think its safe to close this issue after that.

**Comment by OR13** [comment]
please review and close when appopriate.

**Comment by kimdhamilton** [comment]
thanks @OR13! The only other thing was adding lds-jws202 this to the [CCG work items](https://github.com/w3c-ccg/community/blob/master/work_items.md), which I did just now. Closing
