### ISSUE TITLE
[PROPOSED WORK ITEM] Blockchain-Links Specification

### ISSUE THREAD

**Issue by AnthonyRonning** [w3c-ccg/community#114]
# New Work Item Proposal

This specification describes Blockchain Links (Blinks) as a method for referencing blockchain-based data such as transactions and blocks.

## Include Link to Abstract or Draft 

https://www.blockcerts.org/blockchain-links/

Email discussions are linked [here](https://lists.w3.org/Archives/Public/public-credentials/2020Apr/0014.html)

## List Owners

  - myself (@AnthonyRonning)
  - Manu Sporny (@msporny)

**Comment by msporny** [comment]
> I believe Manu wanted to be part of this, just want to confirm (@msporny ?)

+1, Digital Bazaar will support the development of this specification until someone with more cycles comes along. This is important work.

**Comment by AnthonyRonning** [comment]
Thanks @msporny! I'll update the original post.

**Comment by peacekeeper** [comment]
+1 to this work item, this will be useful in a number of ways.

**Comment by peacekeeper** [comment]
+1 to this work item, this will be useful in a number of ways.

**Comment by lemoustachiste** [comment]
+1, interested in following through with this item

**Comment by kimdhamilton** [comment]
we're good to go: https://github.com/w3c-ccg/blockchain-links/
