### ISSUE TITLE
[PROPOSED WORK ITEM] BBS+ Linked Data Proofs

### ISSUE THREAD

**Issue by tplooker** [w3c-ccg/community#115]
# New Work Item Proposal

This specification defines the associated linked data proof suites that can be used to construct digital signatures and proofs using BBS+ with BLS12-381 key pairs. The notable features of these signatures is the ability to "derive a proof" from the original signature enabling selective disclosure. The resulting derived proofs are said to be zero knowledge in nature as they do not reveal the underlying signature for which they are derived from.

## Include Link to Abstract or Draft 

[Draft specification](https://github.com/mattrglobal/jsonld-signatures-bbs-spec)

## List Owners

- Orie Steele @OR13
- Myself @tplooker

**Comment by kimdhamilton** [comment]
Per May 5 2020 call, this has been approved. I ensured Tobias and Kyle are invited to the CCG org with appropriate permissions. (Orie already has access)

@tplooker, @kdenhartog: once you accept the ccg github invitation, you'll have permission to transfer the repositories over to CCG. After you do that, ping us so we can finish the remaining bookkeeping.

**Comment by tplooker** [comment]
Repository has been transferred and links have been updated https://github.com/w3c-ccg/ldp-bbs2020

**Comment by kimdhamilton** [comment]
Boilerplate files added as PR and other setup done. Announce during May 12 call it's adopted and close this issue.
