### ISSUE TITLE
[PROPOSED WORK ITEM] VP Request Spec (for CHAPI etc)

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c-ccg/community#117]
# New Work Item Proposal

See [W3C-CCG New Work Item Process](https://docs.google.com/document/d/1vj811aUbs8GwZUNo-LIFBHafsz4rZTSnRtPv7RQaqNc/edit#)

This data model specification describes a declarative JSON-based query language used by applications to perform requests for Verifiable Presentations to wallets and agents.

The Credential Handler API (CHAPI) spec is an existing Work Item of this community group, and has seen increased implementation and discussion activity recently (for example, the CHAPI and DIDComm overview presentations given at last week's IIW conference resulted in a lot of great questions and expression of interest). And if the CHAPI spec describes a protocol, a simple communication pipe over which apps can communicate with wallets through a web browser, then the VP Request Spec work item proposed in this email, is a data model complement to it.

Is the CHAPI protocol bound to the VP Request Spec data model? No, you can use CHAPI to pass on other types of messages and requests.

Is the VP Request Spec limited only to CHAPI? No, you can use this declarative query syntax with other protocols, such as by wrapping it in DIDComm messages, or by serializing it into URLs, for use with inter-app communication within mobile operating systems.

What is the relationship between the VP Request format and query formats used by DIDComm? That is partly what we hope to explore and come to consensus on in this proposed work item! In general, we believe that these formats can be complementary and inter-operable.

## Include Link to Abstract or Draft 

https://digitalbazaar.github.io/vp-request-spec/

## List Owners

* Dave Longley @dlongley 
* Mike Varley
* Dmitri Zagidulin @codenamedmitri

**Comment by kimdhamilton** [comment]
@dmitrizagidulin since this is accepted, can you transfer over the repo.

**Comment by kimdhamilton** [comment]
@dmitrizagidulin @msporny @dlongley fyi, we need this repo transferred to ccg before it can officially be a work item

**Comment by msporny** [comment]
> @dmitrizagidulin @msporny @dlongley fyi, we need this repo transferred to ccg before it can officially be a work item

Done: https://github.com/w3c-ccg/vp-request-spec/

**Comment by kimdhamilton** [comment]
added boilerplate items and added to work items list. Closing
