### ISSUE TITLE
Choose a screen-sharing platform

### ISSUE THREAD

**Issue by jandrieu** [w3c-ccg/community#126]
SIP has proven problematic *and* doesn't support screen sharing. There's been discussion on the mailing list to potentially move to Zoom or Jitsi, with good points about pros and cons of various options.

The chairs should facilitate a conversation that leads to a decision for the next phase of the group. This conversation comes up every so often and we've developed a lot of tools that help with the current configuration. New options are on the table and the COVID crisis has fueled a push to do it better.

**Comment by kimdhamilton** [comment]
Wayne per 2 June call:
- evaluating different approaches

**Comment by kimdhamilton** [comment]
currently this is tracking jitsi migration

**Comment by kimdhamilton** [comment]
closing; tracking outside
