### ISSUE TITLE
Move Verifiable News Repo to #RebootingWebOfTrust

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#13]
Verifiable News was not formally accepted as a W3C work item and the work ongoing is not happening — this repo should be moved to #RebootingWebOfTrust repo. @manu can you work how to craft an announcement and who to notify?

**Comment by kimdhamilton** [comment]
I moved to the WebOfTrustInfo org: https://github.com/WebOfTrustInfo/verifiable-news

**Comment by kimdhamilton** [comment]
Per May 8 2018 CCG call, chairs will follow up with Sandro Hawke, who may want to take it as part of Verifiable News (or similar effort)

**Comment by kimdhamilton** [comment]
Chairs followed up with Sandro. We will move to an org he prefers if requested
