### ISSUE TITLE
Archive the DID Method Registry Repo

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/community#131]
https://github.com/w3c-ccg/did-method-registry/issues/98

In order to prevent constant PRs, and confusion, the repo should be archived and the existing pull requests should be closed.

People should be directed to open pull requests against https://w3c.github.io/did-spec-registries/ instead.

**Comment by kimdhamilton** [comment]
Updated assignees to review this proposed archiving procedure:
- Redirect github page [as describe here](https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7)
- Move/close issues
- Update README.md, first line should say "This repo has moved to LINK".
- Update website in repo settings
- Mark repo as archived

**Comment by kimdhamilton** [comment]
DID method registry archived according to above procedure.

Chairs to review at our next meeting, then we can move the archiving procedure to our docs location and close this issue.

**Comment by kimdhamilton** [comment]
Instructions added [here](https://github.com/w3c-ccg/w3c-ccg.github.io/blob/master/archive_work_item.md)
