### ISSUE TITLE
Status of Verifiable Credentials JSON Schemas

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#132]
- Verifiable Credentials JSON Schemas
- Rough draft
- Plan/Schedule
- Is it examples or registry?

https://lists.w3.org/Archives/Public/public-credentials/2019Oct/att-0033/workday-credential-schemas.md

**Comment by ChristopherA** [comment]
Also, how does this relate to #97?

**Comment by kimdhamilton** [comment]
dupe of #97
