### ISSUE TITLE
DID Resolution

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#134]
- What is current status?
- will we see an interim draft?

**Comment by ChristopherA** [comment]
I know that DID Resolution, or at least some parts of it, might be moved to the W3C DID WG. If it is, I'd like to see some interim draft pegged to be a CCG Final Report before officially passing the work on the the DID WG.

I consider the list of Final Reports to be the CCGs "brag" list to demonstrate to future participants of the CCG of the merits of engaging in our processes.  

-- Christopher Allen

**Comment by peacekeeper** [comment]
The idea is that the "interfaces" or "contracts" of DID Resolution (and DID URL Dereferencing) will be moved to the DID Core spec in the DID WG. This is taking a bit longer than expected, but PRs are actively being discussed in the DID WG right now:
https://github.com/w3c/did-core/pulls?q=is%3Apr+is%3Aopen+label%3Acontract

We also have this on the agenda for tomorrow's DID Resolution call:
https://docs.google.com/document/d/1qYBaXQMUoB86Alquu7WBtWOxsS8SMhp1fioYKEGCabE/

In any case, the DID Resolution spec will continue to exist, it may just change slightly in scope.

**Comment by kimdhamilton** [comment]
we can close this; it was just tracking discussion of latest status, which we got
