### ISSUE TITLE
Status of ocaps/zcaps/etc

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#135]
- I renamed the work item link from ocap to zcap because links were dead. Was this correct? Now points to https://w3c-ccg.github.io/zcap-ld/ 
- What is the intended work item now? 
- What is the status?

Current owners are listed as the following. Are they still current? 2/3 are not active members.
- Christopher Lemmer Webber (Spec-Ops)
- Manu Sporny (Digital Bazaar)
- Mark S. Miller (Agoric)

**Comment by ChristopherA** [comment]
I've considered requesting to be a co-owner on this work item, however first:

a) I'd like to see this first that this document be at least current with implementation.

b) Confirm that there is interest from current owners and implementors  to moving toward a form that can work with futures like Lightning LSATs. They may say they just want to have this more limited cap spec get to final report.

If not, I may seek a co-owner for a different work item for a broader form of standard for directed object capabilities.

-- Christopher Allen

**Comment by wyc** [comment]
This is superseded by the process described in w3c-ccg/workitem-process. Please re-open if you'd like to continue this discussion or need support.
