### ISSUE TITLE
Organize Asia Pacific (APAC) Meeting

### ISSUE THREAD

**Issue by wyc** [w3c-ccg/community#139]
Hi, I am surveying for the best W3C CCG meeting time for APAC members. My current proposal is 1 hour on Wednesdays at 8:00 AM UTC+8. This would mean:

APAC:
* Singapore: 8 AM
* Beijing, China: 8 AM
* Seoul, South Korea: 9 AM
* Tokyo, Japan: 9 AM
* Sydney, Australia: 10 AM
* Wellington, New Zealand: 12 PM

Non-APAC:
* San Francisco, USA: 5 PM
* New York, USA: 8 PM
* Berlin, Germany: 2 AM

Any thoughts or feedback?

**Comment by wyc** [comment]
in case anyone can share some wisdom or loop in some relevant others, cc @tplooker @Korsimoro @burnburn

**Comment by wyc** [comment]
We have the Jitsi working, so will resume this and schedule the first one soon.

**Comment by wyc** [comment]
We will likely revisit this after the election, the chairs must in the meanwhile conduct outreach to gather the right interest from APAC membership and we currently have simultaneous projects running, including https://github.com/w3c-ccg/community/issues/168 . We are continuing to track this during chair meetings.

**Comment by wyc** [comment]
Now that https://github.com/w3c-ccg/infrastructure is running, we can consider picking a date in March and conducting our first CCG meeting then.

**Comment by tkendal** [comment]
@wyc, we have a fairly mature group via [AP-Lab](https://www.learningeconomy.io/node/asia-pacific-lab). Happy to inquire if any feedback is still needed regarding timing. I imagine a handful would be interested and likely attend regularly.

**Comment by vsnt** [comment]
Update: this issue is on hold until we have a new co-chair.
