### ISSUE TITLE
Communication / Culture

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#140]
- https://w3c.github.io/PWETF/
- https://www.recurse.com/social-rules
- https://www.w3.org/2020/05/CEPC

**Comment by wyc** [comment]
https://tools.ietf.org/html/rfc7704

**Comment by vsnt** [comment]
W3C Positive Work Environment (PWE) - new code of ethics and code of conduct - July 2020. https://w3c.github.io/PWETF/
Inclusion and Diversity Group: https://www.w3.org/community/idcg/

**Comment by wyc** [comment]
from DIF: https://github.com/decentralized-identity/org/blob/master/code-of-conduct.md

**Comment by kimdhamilton** [comment]
Addressing as part of diversity strategy preliminary research
