### ISSUE TITLE
Update to recommended cg-license

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#142]
Our repos include a default LICENSE.md which contains only the first sentence of the text of [W3C's recommended CG-LICENSE](https://github.com/w3c/licenses/blob/main/CG-LICENSE.md).

We need to update this file in all current repos and update the repo generation script to use the recommended license.

**Comment by kimdhamilton** [comment]
Additional option for Apache / mixed licenses. Chairs to discuss.

All Reports in this Repository are licensed by Contributors under the [W3C Software and Document
License](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document).

Contributions to Specifications are made under the
[W3C CLA](https://www.w3.org/community/about/agreements/cla/).

Contributions to Software, including sample implementations, are under the
[Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0)

**Comment by kimdhamilton** [comment]
Confirmed from Wendy that we can make the Apache/mixed license the default.

**Comment by kimdhamilton** [comment]
- Update all repos
- Update "scripts"

**Comment by kimdhamilton** [comment]
In general, we should check all imported repos (DVCG) -- or all repos, if easier -- have correct [boilerplate setup](https://w3c-ccg.github.io/create_repo.html)

**Comment by wyc** [comment]
I still need to write a script to crawl the repos and maybe even auto-PR the right license.

**Comment by wyc** [comment]
Will be done by the 10th.

**Comment by wyc** [comment]
Jitsi has caused this to be delayed because it took priority, my apologies. To allow me to focus on the Infrastructure Task Force, @vsnt has offered to take this task manually. Thanks @vsnt .

**Comment by vsnt** [comment]
I have updated all the repos in the CCG folder with the updated license with *the following EXCEPTIONS* because they already had a license specified. 

https://github.com/w3c-ccg/sovrin/blob/master/LICENSE : Apache 2.0 license
https://github.com/w3c-ccg/did-test-suite/blob/master/LICENSE : BSD-3
https://github.com/w3c-ccg/lds-merkle-proof-2019/blob/master/LICENSE : MIT License
https://github.com/w3c-ccg/lds-rsa2018/blob/gh-pages/LICENSE : BSD-3 license
https://github.com/w3c-ccg/lds-ed25519-2018/blob/gh-pages/LICENSE : BSD-3 license

Do these need to be updated with the boilerplate license or are the ok as-is? If they are ok, this issue can be closed.

**Comment by vsnt** [comment]
@kimdhamilton can you take a look at the previous comment and advise. Thank you.

**Comment by kimdhamilton** [comment]
There are two issues:
- I thought [lds-merkle-proof-2019](https://github.com/w3c-ccg/lds-merkle-proof-2019) was retired/archived. I created an issue to track this: https://github.com/w3c-ccg/community/issues/176, so that won't block this issue
- Checkbox item 3 still isn't done (for example, I noticed lds-merkle-proof-2019 didn't have the boilerplate files), but it's ok to create a separate issue to track that so you can close this

**Comment by vsnt** [comment]
@kimdhamilton thanks for the update and opening the issue re: lds-merkle-proofs. However I still lack clarity on the other repos mentioned in https://github.com/w3c-ccg/community/issues/142#issuecomment-751925176, which list 5 repos that use non CCG licenses. 

Since these repos have already specified a license, do they go with their specified license or get the CCG boilerplate one?

**Comment by vsnt** [comment]
> I have updated all the repos in the CCG folder with the updated license with _the following EXCEPTIONS_ because they already had a license specified.
> 
> https://github.com/w3c-ccg/sovrin/blob/master/LICENSE : Apache 2.0 license
> https://github.com/w3c-ccg/did-test-suite/blob/master/LICENSE : BSD-3
> https://github.com/w3c-ccg/lds-merkle-proof-2019/blob/master/LICENSE : MIT License
> https://github.com/w3c-ccg/lds-rsa2018/blob/gh-pages/LICENSE : BSD-3 license
> https://github.com/w3c-ccg/lds-ed25519-2018/blob/gh-pages/LICENSE : BSD-3 license
> 
> Do these need to be updated with the boilerplate license or are the ok as-is? If they are ok, this issue can be closed.

I have either put in a pull request or opened an issue to update the licenses on these outstanding repos.

**Comment by vsnt** [comment]
> There are two issues, but here are options to proceed with closing it.
> 
> * I thought [lds-merkle-proof-2019](https://github.com/w3c-ccg/lds-merkle-proof-2019) was retired/archived. I created an issue to track this: #176, so that won't block this issue
> * Checkbox item 3 still isn't done (for example, I noticed lds-merkle-proof-2019 didn't have the boilerplate files), but it's ok to create a separate issue to track that so you can close this afterward (link from here)

The merkle-proof repo was referenced in the previous comment of repos that were outstanding due to already having a license applied.

**Comment by vsnt** [comment]
Heya @wyc @kimdhamilton can you please review https://github.com/sovrin-foundation/sovrin/pull/288 and advise on resolving? Thanks.

**Comment by msporny** [comment]
These repositories can use the CCG license:

https://github.com/w3c-ccg/did-test-suite/blob/master/LICENSE : BSD-3
https://github.com/w3c-ccg/lds-merkle-proof-2019/blob/master/LICENSE : MIT License
https://github.com/w3c-ccg/lds-rsa2018/blob/gh-pages/LICENSE : BSD-3 license
https://github.com/w3c-ccg/lds-ed25519-2018/blob/gh-pages/LICENSE : BSD-3 license

The CCG did-test-suite repo needs to 1) have the license updated, 2) redirect to the official W3C DID WG Test Suite, and 3) be archived:

https://github.com/w3c-ccg/did-test-suite/blob/master/LICENSE : BSD-3

The location of the official did-test-suite repo is here:

https://github.com/w3c/did-test-suite/

**Comment by vsnt** [comment]
It's DONE!
