### ISSUE TITLE
Work Item requires editors from independent companies

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/community#146]
@msporny you are the only editor listed for this work item.

There is no CODEOWNERS...

We need to fix this, I suggest we create CODEOWNERs, list you and I as owners to start, and add me as an editor to spec / vocab...

I would also invite @tplooker to be added.

**Comment by kimdhamilton** [comment]
Moving to CCG community repo as this is a group process issue. We'll discuss on the 8/4 call

**Comment by msporny** [comment]
I'm fine w/ @OR13 and @tplooker being added to any CCG security spec that doesn't already have multiple contributors from different orgs.

The reason this happened is because the LD Security specs predate this CCG requirement.

**Comment by kimdhamilton** [comment]
8/4 add Tobias and ORie, and we'll close.

**Comment by kimdhamilton** [comment]
Added Tobias and Orie
