### ISSUE TITLE
[PROPOSED WORK ITEM] universal-wallet-2020

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#149]
# New Work Item Proposal

See [W3C-CCG New Work Item Process](https://docs.google.com/document/d/1vj811aUbs8GwZUNo-LIFBHafsz4rZTSnRtPv7RQaqNc/edit#)

## Include Link to Abstract or Draft 

- Proposal from [CCG email archives](https://lists.w3.org/Archives/Public/public-credentials/2020Jun/0158.html)
- Repo: https://github.com/transmute-industries/universal-wallet
- Spec: https://transmute-industries.github.io/universal-wallet/

## List Owners

> Identify 1 lead (person responsible for advancing the work item) and at least 1 other owner. Ideally, include their github usernames

- @OR13, Transmute
- @kimdhamilton, Digital Credentials Consortium / MIT
- @mprorock, Mesur.io

**Comment by kimdhamilton** [comment]
Questions for @OR13:
- Please confirm work item/repo name "universal-wallet-2020"
- Would you like to transfer the repo or have chairs create a new one?

**Comment by kimdhamilton** [comment]
Question for Learning Economy -- we need codeowner alias(es)

**Comment by OR13** [comment]
Sorry for the late reply, we should create a new repo, I will merge git histories and setup redirects to prevent broken links.

we should probably call the repo "universal-wallet-interop-spec" or something like that, we've gotten lots of feedback that the spec name sounds too much like a vendor's product.... we can always rename later...

**Comment by kimdhamilton** [comment]
Learning Economy: ntonani

**Comment by kimdhamilton** [comment]
Created boilerplate repo here: https://github.com/w3c-ccg/universal-wallet-interop-spec
