### ISSUE TITLE
[PROPOSED WORK ITEM] Ed25519 Signature 2020 

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/community#151]
# New Work Item Proposal:  Ed25519 Signature 2020 

https://lists.w3.org/Archives/Public/public-credentials/2020Sep/0008.html

##  Draft 

https://transmute-industries.github.io/vc.js/ed25519-signature-2020/
https://github.com/transmute-industries/vc.js/tree/master/packages/ed25519-signature-2020

## Owners

@OR13
@msporny 
@tplooker

**Comment by wyc** [comment]
Looks like we have more than one owner, and the chairs have decided to welcome this work item. Is there a preferred GitHub repository name? It seems that `ed25519-signature-2020` is the current proposed.

**Comment by msporny** [comment]
Let's try to align w/ the other specs... lds-ed25519-2020

**Comment by wyc** [comment]
As mentioned on the call today, we will create a repository this week with the owners above and add this as a CCG work item.

**Comment by wyc** [comment]
Hi, I've added a new repository here with the work item owners granted the appropriate permissions: https://github.com/w3c-ccg/lds-ed25519-2020

I have also added this to the list of work items in the community repo: https://github.com/w3c-ccg/community/pull/152

Please let me know if you would like any additional help with repository setup, but as a reminder here are some helpful links as to what I've done so far and how to work with respec:
- https://github.com/w3c-ccg/w3c-ccg.github.io/blob/master/create_work_item.md
- https://w3c-ccg.github.io/respec.html
