### ISSUE TITLE
[PROPOSED WORK ITEM] Citizenship Vocabulary

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/community#155]
# New Work Item Proposal

This specification describes a Linked Data vocabulary for asserting Verifiable Credentials related to citizenship information, such as given name, family name, country of citizenship, birthday, and other attributes used to determine the citizenship status of a citizen.

## Include Link to Abstract or Draft 

https://digitalbazaar.github.io/citizenship-vocab/

## List Owners

* Lead - Manu Sporny, Digital Bazaar (@msporny)
* Owner - Dave Longley, Digital Bazaar (@dlongley)
* Owner - Mike Varley, Secure Key (@mavarley)

**Comment by peacekeeper** [comment]
We (Danube Tech) are also interested in contributing to this Work Item.

**Comment by lrosenthol** [comment]
Seems like a very useful vocabulary, but I would think that having a formal JSON Schema for the grammar instead of the text as currently proposed would be much more useful (both for humans and machines).

**Comment by wmclaxton** [comment]
NextID in Singapore is following this Work Item.  It will be relevant to parallel efforts by Singapore government.

**Comment by kimdhamilton** [comment]
- Repo is initialized with boilerplate files here: https://github.com/w3c-ccg/citizenship-vocab
- Added to work item list
