### ISSUE TITLE
[PROPOSED WORK ITEM] Traceability Vocabulary

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/community#156]
# New Work Item Proposal

## Abstract or Draft 

previous work on this was done here: 
- https://github.com/w3c-ccg/vc-examples/tree/master/docs/cmtr
- https://github.com/w3c-ccg/vc-examples/tree/master/docs/crude

Attempting to revise / consolidate the vocabulary, based on the initial work:

https://transmute-industries.github.io/traceability-vocab

## List Owners

@OR13
@mprorock
@mkhraisha

**Comment by jstclair2019** [comment]
Count me in, please

**Comment by OR13** [comment]
@kimdhamilton can I move our repo here, and fix any of the links?

**Comment by OR13** [comment]
@kimdhamilton if you prefer to just setup the "boilerplate" I can merge github histories.

https://github.com/transmute-industries/traceability-vocab/blob/master/LICENSE.md

**Comment by OR13** [comment]
mainly I just want to move the repo and fix the broken links (w3id.org setup).

**Comment by jstclair2019** [comment]
Sounds good. I want to try and move forward on this and I think a new repo would help, thanks!

**Comment by kimdhamilton** [comment]
- Repo is here: https://github.com/w3c-ccg/traceability-vocab
- Added to work items list

**Comment by TallTed** [comment]
Maybe this should be retitled, **[CONFIRMED WORK ITEM]** or some such?  And the labels on this issue updated to reflect current status?

**Comment by wyc** [comment]
Thanks for the suggestion @TallTed

**Comment by TallTed** [comment]
Halfway there, @wyc.  I think the labels `action: review next` and `proposed work items` also need to change (either by being taken off, or by being changed to currently appropriate labels [which I can't suggest well, because I can't see what labels exist]).
