### ISSUE TITLE
Revisit CCG work item templates as github templates

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#158]
We already have this for bikeshed repos, but let's make a general one too. This will avoid needing the create-repo script

**Comment by wyc** [comment]
This is a good idea. Here's relevant documentation: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

Is there someone who would like to work on this? Could be a great first contribution.

**Comment by vsnt** [comment]
We will discuss at 1/6/2021: 10am PT / 1pm ET meeting. Details: https://lists.w3.org/Archives/Public/public-credentials/2020Dec/0208.html

**Comment by kimdhamilton** [comment]
I updated the original description to clarify and make it more actionable

**Comment by kimdhamilton** [comment]
Relevant:
- current create work item instructions: https://github.com/w3c-ccg/w3c-ccg.github.io/blob/master/create_work_item.md
- should we add boilerplates for respec? https://github.com/w3c-ccg/vc-status-rl-2020/blob/master/common.js

**Comment by vsnt** [comment]
@msporny and I recently updated the new work item template with the new work item requirements. Does that satisfy this issue? Or is this the request to create a repo template? cc @kimdhamilton

**Comment by kimdhamilton** [comment]
I think that's fine. I'll close this
