### ISSUE TITLE
Keep the meeting location public, accessible, and up to date.

### ISSUE THREAD

**Issue by wyc** [w3c-ccg/community#160]
* Possibly add a public calendar invite with the correct meeting information. (@kimdhamilton suggested this)

**Comment by kimdhamilton** [comment]
I just did this for VC-EDU under our w3c-ccg google account. [VC-EDU public calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=N2JucGsxYWlkOHZqcGswcWhmbTRjbmpiMDRfMjAyMDExMDJUMTYwMDAwWiA2YTRicTE3bm84NHNzbmFkY2NtMGoyMTMzZ0Bn&tmsrc=6a4bq17no84ssnadccm0j2133g%40group.calendar.google.com&scp=ALL)

We can do this for CCG as well

**Comment by tkendal** [comment]
This brings me more joy than it should...thank you @kimdhamilton 🙏

**Comment by wyc** [comment]
During our chair meeting, @vsnt indicated interest in figuring this out.

**Comment by vsnt** [comment]
Here is the CCG google calendar: https://calendar.google.com/calendar/u/1?cid=ZTE4N2hnNDFocm1zZG4zM2xwMjQ3NWNwOTBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

Closing this item.
