### ISSUE TITLE
CCG Feedback Survey

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#162]
Survey to gather feedback on the CCG.
Formal work item to figure out what to do next re: a CCG survey for TPAC & general presenter feedback: https://www.surveymonkey.com/r/JXHKBJ7

This work item could also be an ongoing open item to gather feedback from the CCG at various times, e.g. end of year, Jitsi vs Zoom, etc. 

Owner: @vsnt 
Lead: @vsnt 

See [W3C-CCG New Work Item Process](https://docs.google.com/document/d/1vj811aUbs8GwZUNo-LIFBHafsz4rZTSnRtPv7RQaqNc/edit#)

**Comment by wyc** [comment]
Hi Heather, I'd like to be a co-owner of this item if you'll have me.

**Comment by vsnt** [comment]
Answering additional work item questions:

1. What are you trying to do? Articulate your objectives using absolutely no jargon.
Have a standard way to gather information from the Credentials Community Group.

2. How is it done today, and what are the limits of current practice?
The Credentials Community Group gathers community information ad-hoc via the email list or during meetings. @vsnt has conducted several ad-hoc survey's in the past.

3. What is new in your approach and why do you think it will be successful?
Regular feedback mechanism that can be duplicated on conducted at a regular basis.

4. Who cares? If you are successful, what difference will it make?
This will help the chairs run a more successful community group for the community.

5. What are the risks?
There are few risks and this is not a blocker for other tasks.

6. How much will it cost?
Currently using @vsnt's SurveyMonkey account. 

7. How long will it take?
It is an ongoing project. Individual projects can take 4-6 weeks.

8. What are the mid-term and final “exams” to check for success?
On a per project basis.

9. How are you involving participants from multiple skill sets in this work item? (technical, design, product, marketing, anthropological, UX)
Depending on the survey topic specific, we will recruit an appropriate team.

10. How are you involving participants from various global locations in this work item? (Americas, Euro, Asia-Pacific, South America)
Great, question. To date, we are soliciting from the CCG group, which has limited global participation.

11. How do you plan to involve non-technical subject matter experts & end users of your work item? How will you work item improve their lives?
It should not be a problem to involve technical and non-technical subject matter experts - AND as well to solicit answers from both groups.

12. What actions are you taking to make this work item accessible to a non-technical audience?
This work item should be easily accessible to a non-technical audience.

**Comment by tkendal** [comment]
@vsnt Open to supporting this as well. Is this distinct from #161 or perhaps could be merged? Seems perhaps a mechanism to inform/prioritize 101 materials.

**Comment by vsnt** [comment]
@tkendal - it's different, but they can support each other. This is a more general work item for feedback surveys. But not limited to new materials.

**Comment by longpd** [comment]
Happy to contribute to this to get my feet wet  ;-) and maybe help some, too.

**Comment by kimdhamilton** [comment]
approved on 17 Nov meeting; @vsnt and @wyc to create using https://w3c-ccg.github.io/create_work_item.html

**Comment by vsnt** [comment]
Hi, I'd like to suggest we close this item and roll any work into https://github.com/w3c-ccg/community/issues/161. 

(I think @kimdhamilton 's comment above was supposed to be on 161 instead.)
