### ISSUE TITLE
Chairs to add task force documentation to process doc

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#164]

**Comment by vsnt** [comment]
This work item is to document what is required of task forces, since the CCG has three different ones as of Nov 2020. There have been requests for new task forces, but we need to codify the requirements before considering new ones.

**Comment by vsnt** [comment]
Draft ready for chair review.

**Comment by vsnt** [comment]
[Task Force FAQ Draft](https://docs.google.com/document/d/1QBSskibwdgpE5UCXLA9iYm7jJNEZNhKTZyK7srFuMUc/edit?usp=sharing) is complete and publicly available. Should review/email to the community. Propose to close item.

**Comment by vsnt** [comment]
We will discuss at 1/6/2021: 10am PT / 1pm ET meeting. Details: https://lists.w3.org/Archives/Public/public-credentials/2020Dec/0208.html

**Comment by kimdhamilton** [comment]
Next steps:
- Community review of text in the google doc
- Submit the (approved) text as a PR to https://github.com/w3c-ccg/w3c-ccg-process since we need it in spectext

From discussion here: https://github.com/w3c-ccg/community/issues/172#issuecomment-753682795

**Comment by vsnt** [comment]
Reviewed and accepted at 1/27 call. https://w3c-ccg.github.io/workitem-process/
