### ISSUE TITLE
Create job description/instruction manual for W3C CCG Chairing

### ISSUE THREAD

**Issue by wyc** [w3c-ccg/community#165]
We want to reduce our bus factor and ease transitions as co-chairs.

**Comment by vsnt** [comment]
I am actively working on a draft of this and will have something to share by next CCG meeting.

**Comment by vsnt** [comment]
First draft complete, going for internal chair review.

**Comment by vsnt** [comment]
This is complete and available here. I'll share to the list in a bit. https://docs.google.com/document/d/18uPGjBw15i9jLRQ5K4SCwrrGU6zBIB3PpIap17X39fo/edit?usp=sharing
