### ISSUE TITLE
Create namespace and npmjs repo for w3c-ccg

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/community#166]
https://www.npmjs.com/package/@w3c-ccg <- this namespace does not exist (yet), would need to have it be created and setup to accept this PR.

... also a question for the CCG Chairs, since this is probably more of their wheel house.

@w3c-ccg/chairs 

I am happy to help set this up, but it would make the CCG responsible for software packages / security updates / npm tokens, etc...

_Originally posted by @OR13 in https://github.com/w3c-ccg/universal-wallet-interop-spec/pull/44#issuecomment-725461987_

**Comment by brianwmunz** [comment]
Hi, just wondering if there's any updates on this?  @wyc @kimdhamilton @vsnt

**Comment by wyc** [comment]
@brianwmunz We will discuss next steps here tomorrow. There is likely something we can do in the short term as we await https://github.com/w3c-ccg/community/issues/168 to resolve. Thank you for your patience and apologies for the deoay.

**Comment by kimdhamilton** [comment]
1. do we want to do it? 
2. is it part of task force?

in scope: test suites, reference data

**Comment by wyc** [comment]
1. Yes
2. Yes

The scope looks correct. Pending close of #168, so we can handle it in the Infrastructure TF.

**Comment by wyc** [comment]
Tracking this in the ITF: https://github.com/w3c-ccg/infrastructure/issues/1
