### ISSUE TITLE
Code of conduct reference in w3c-ccg repos

### ISSUE THREAD

**Issue by brianwmunz** [w3c-ccg/community#169]
# New Work Item Proposal

See [W3C-CCG New Work Item Process](https://docs.google.com/document/d/1vj811aUbs8GwZUNo-LIFBHafsz4rZTSnRtPv7RQaqNc/edit#)

## Include Link to Abstract or Draft 

While there is a [code of conduct ](https://www.w3.org/Consortium/cepc/) referenced for w3c, it is a common practice to have a code of conduct in individual repositories.  Should we make it a requirement for existing and future w3c-ccg repositories to include a code of conduct? @w3c-ccg/chairs

## List Owners
@brianwmunz

**Comment by vsnt** [comment]
This appears to be a request to add the code of conduct as a requirement to all new work items. This would be an additional CCG work item requirement and we could use our standard CCG code of conduct or the PWE code.

We should discuss at a future meeting.

**Comment by vsnt** [comment]
@brianwmunz would you be willing to speak about this on Jan 5, during our meeting? Thanks.

**Comment by brianwmunz** [comment]
Sure, sounds good.

**Comment by vsnt** [comment]
Great! Thank you @brianwmunz

**Comment by vsnt** [comment]
We will discuss at 1/6/2021: 10am PT / 1pm ET meeting. Details: https://lists.w3.org/Archives/Public/public-credentials/2020Dec/0208.html

@brianwmunz - please note the day & time change. Will you be able to make this? Thanks.

**Comment by brianwmunz** [comment]
That works for me.  Thanks.

**Comment by vsnt** [comment]
Discussed at 1/6/2021 meeting, no issues. 
Manu says, W3C WG already reference this, so CCG can look to see how this is done and replicate. Could also include in licenses information.

**Comment by msporny** [comment]
Here is how W3C Working Groups do it:

https://github.com/w3c/did-core/blob/main/CODE_OF_CONDUCT.md

They create a file called CODE_OF_CONDUCT.md that links to the W3C document. 

They then reference that from their top-level README.md:

https://github.com/w3c/did-core#code-of-conduct

This can all be automated through a Github new project template.

**Comment by vsnt** [comment]
@brianwmunz what's your LinkedIn profile (for the mintues)? Thanks.

**Comment by ChristopherA** [comment]
Note that you can add a repo called `.GitHub` in the community, and its contents are then shown in EVERY repo in that community (unless overridden by a local file). See  https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file

**Comment by vsnt** [comment]
Reviewed and accepted at 1/27 call. https://w3c-ccg.github.io/workitem-process/
