### ISSUE TITLE
VC PRs under maintenance charter

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#170]
We need to discuss how to move this forward in an upcoming CCG meeting: https://github.com/w3c/vc-data-model/pull/752

See https://github.com/w3c/vc-data-model/pull/752#issuecomment-738544810 for details.

FYI @msporny @burnburn @iherman @wyc @vsnt

**Comment by wyc** [comment]
On the weekly call, @msporny says that what need to do next is to communicate our process to W3C staff and come to alignment.

Involved parties: Chairs of the CCG, W3C Staff Contact, VC Editors

**Comment by kimdhamilton** [comment]
After holidays convene a meeting

**Comment by wyc** [comment]
We chairs need to convene a meeting with W3C Staff Contact (@iherman?) and VC editors. I will coordinate one.

**Comment by iherman** [comment]
> We chairs need to convene a meeting with W3C Staff Contact (@iherman <https://github.com/iherman>?) and VC editors.
> 
+ the VC WG Chair (Dan Burnett).

And yes, I am indeed the staff contact.

> I will coordinate one.
>

**Comment by vsnt** [comment]
FYI, found this repo that may be relevant: https://github.com/w3c-ccg/vcwg-maintenance

**Comment by wyc** [comment]
The next step here is to convene a meeting with @iherman, @burnburn, and the chairs.

I've made a Doodle for this discussion: https://doodle.com/poll/5htdqd4ypxp8mdb4

**Comment by vsnt** [comment]
Sent an email and copying here, reply wherever is easiest: which of the following day/time are you available for this discussion? @iherman @wyc @kimdhamilton @burnburn @msporny 

Week of Feb 1
- Feb 2, 11am PT / 1pm ET / 8pm CET
- Feb 3, 8am PT / 11am ET / 5pm CET
- Feb 3, 9am PT / Noon ET / 6pm CET
- Feb 4, 8am PT / 11am ET / 5pm CET
- Feb 5, 8am PT / 11am ET / 5pm CET
- Feb 5, 9am PT / Noon ET / 6pm CET

Week of Feb 8
- Feb 10, 8am PT / 11am ET / 5pm CET
- Feb 10, 9am PT / Noon ET / 6pm CET
- Feb 11, 8am PT / 11am ET / 5pm CET
- Feb 11, 9am PT / Noon ET / 6pm CET
- Feb 12, 8am PT / 11am ET / 5pm CET
- Feb 12, 9am PT / Noon ET / 6pm CET

**Comment by vsnt** [comment]
@burnburn @msporny @iherman @kimdhamilton @wyc & @brentzundel met on 2/11. Next steps will be added in separate issues. Recapping them here:
- CCG will document a work item process for maintenance work (@vsnt)
- CCG will formally announce a meeting for PRs for VC Maintenance & VC Maint Chairs (@brentzundel & @wyc) will hold a meeting to discuss.
