### ISSUE TITLE
Ensure task force creation process captures need for a charter

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#172]
Details are here: https://github.com/w3c-ccg/community/issues/168#issuecomment-747643157

**Comment by vsnt** [comment]
We'll address this in the Chairs-Only (for now) Task Force FAQ https://docs.google.com/document/d/1QBSskibwdgpE5UCXLA9iYm7jJNEZNhKTZyK7srFuMUc/edit

**Comment by vsnt** [comment]
[Task force FAQ](https://docs.google.com/document/d/1QBSskibwdgpE5UCXLA9iYm7jJNEZNhKTZyK7srFuMUc/edit?usp=sharing) is public and addresses this request. Propose to close this item.

**Comment by vsnt** [comment]
Hi @kimdhamilton, do the additions to the task force FAQ satisfy this ask? If there are no issues, we will close on Dec 28, 2020.

**Comment by vsnt** [comment]
We will discuss at 1/6/2021: 10am PT / 1pm ET meeting. Details: https://lists.w3.org/Archives/Public/public-credentials/2020Dec/0208.html

**Comment by TallTed** [comment]
[Task Force FAQ](https://docs.google.com/document/d/1QBSskibwdgpE5UCXLA9iYm7jJNEZNhKTZyK7srFuMUc/edit?usp=sharing) needs a little editing.

Fo this reason among others, I think this and other docs produced by the CCG belong in Github, rather than Google Docs (where this is now public but READ-ONLY), so that we can make relevant PRs/suggestions without adding substantial burden to the doc owners (tracking Google IDs vs Github IDs, etc.).

**Comment by vsnt** [comment]
Hi @TallTed, happy to give you comment access where you can make suggestions without burdening writers with a system that was not developed for their use case in mind... send a request via google docs and I'll approve.

**Comment by kimdhamilton** [comment]
@TallTed has a point here. Documents describing how the CCG is run should be in spectext. The difference is:
- For an individual task force charter (DID resolutions, etc), we've historically allowed that to be in a google doc or something lighter weight
- Documents that track how the CCG operates (i.e. the process of creating a task force) should be carefully tracked, and our convention is to use respec

We already have a good place to add it, which is: https://github.com/w3c-ccg/w3c-ccg-process

**Comment by vsnt** [comment]
@vsnt to re-add this text, which was accidentally removed from the previous change. https://github.com/w3c-ccg/workitem-process & https://w3c-ccg.github.io/workitem-process/

**Comment by vsnt** [comment]
This has been added to the workitem-process charter. https://w3c-ccg.github.io/workitem-process/
