### ISSUE TITLE
Retire or fix the lds-merkle-proof-2019 work item

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#176]
I noticed several problems with the [lds-merkle-proof-2019](https://github.com/w3c-ccg/lds-merkle-proof-2019) repo. 

- It's missing the CCG boilerplate files
- It has the wrong license
- I am still listed as an author, but am no longer supporting/maintaining this effort. 

If you are interested in being an owner, please respond to this so you can be added as an owner. Otherwise we will archive and retire this work item

**Comment by dsemenovsky** [comment]
Hi @kimdhamilton 

I’d like to take over the ownership over the repo, please.

**Comment by kimdhamilton** [comment]
Thanks @dsemenovsky, that's great. I should have mentioned -- ccg work items require 2 owners from different orgs. So we need one more to sign on.

Based on recent activity, I'm wondering if @lemoustachiste would want to be an owner? Not sure if Blockcerts is still relying on this,

**Comment by lemoustachiste** [comment]
Hi @kimdhamilton, 

I guess it would make sense, we are still working with it indeed. 

Thanks

**Comment by vsnt** [comment]
ToDo

- [ ] Add missing work item template files
- [ ] Update license
- [ ] Add @lemoustachiste & @dsemenovsky as owners

**Comment by vsnt** [comment]
@dsemenovsky @lemoustachiste can you please confirm you have maintain access on the https://github.com/w3c-ccg/lds-merkle-proof-2019 repo? Once confirmed we can close this issue. Thank you.

**Comment by vsnt** [comment]
Fixed and closing.
