### ISSUE TITLE
lds repo folder clean up/consolidation

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#178]
There are a lot of top level lds folder - one for each method. This makes the overall CCG repo very messy. I would like to clean it up and propose grouping lds related projects in a main folder. 

Brought this issue up at Jan 13 meeting and @msporny had some comments. I would also like to hear comments by @OR13, @wyc and others. Thanks.

**Comment by OR13** [comment]
do you mean `lds-` repos? like making a `lds-` mono repo?

there are some in DIF as well, the idea is that you can create one anywhere.

**Comment by vsnt** [comment]
Closing this issue, as probably not useful use of chair time.
