### ISSUE TITLE
JWK cryptosuite specifications

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#18]
**See updated action items below**

This issue is from @msporny feedback from [CCG meeting on 1 May 2018](https://w3c-ccg.github.io/meetings/2018-05-01/).

Action items for uPort:
1. Create a spec that demonstrates how you express a JWK using a LD Cryptosuite.
2. Create a spec that demonstrates how you express a Verifiable Credential as a JWT
3. Implementations and test suites for those specs

And push this through IETF

**Comment by dmitrizagidulin** [comment]
For reference: [Minutes from the first JWT Task Force call](https://www.w3.org/2018/11/19-vcwg-minutes.html)

**Comment by kimdhamilton** [comment]
We may not have critical mass to make this a work item, but we can satisfy the first two. Kim to drive through DIF

**Comment by ChristopherA** [comment]
Almost a year later — what is the status on these? If no progress or report, we will close these work items in 30 days.

**Comment by David-Chadwick** [comment]
Number 2. in your list is already part of the VC Data model (see https://www.w3.org/TR/vc-data-model/#proof-formats). This shows how to create both VCs and VPs as JWTs. I understand (though I have not tested it myself) that the JWT encoding is tested but not the signature validation because this was ruled to be out of scope of the VC spec (i.e. no signature suites are standardised).

**Comment by OR13** [comment]
Here is an example of creating JWTs using the VC Data Model, and JWK... https://github.com/decentralized-identity/interoperability/tree/master/projects/cli-demo

IMO we should still close the issue, the DID Core and VC Data Model both support JWK now, AFAIK.

**Comment by ChristopherA** [comment]
@OR13 I'd like to close this issue but feel there needs to be some place to list your tools and other tools, so that others can find it. Is there a good exiting repo in the CCG for this, or do we need to create a new one? Can you make a suggestion at next CCG meeting? Thanks!

**Comment by OR13** [comment]
They are listed here: https://github.com/w3c-ccg/ld-cryptosuite-registry
