### ISSUE TITLE
Create work item process for maintenance mode of inactive WGs

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#180]
Addressing a request from the resolution of #170 (https://github.com/w3c-ccg/community/issues/170)
- [ ]  CCG will document a work item process for maintenance work (@vsnt)

**Comment by vsnt** [comment]
Attn @wyc @brentzundel

**Comment by wyc** [comment]
The only maintenance group right now is the VC WG, so I will be creating a work item that describes this process this week.

**Comment by vsnt** [comment]
@wyc has handled this, so I'm closing.
