### ISSUE TITLE
Schedule VC Maint meeting to discuss PRs for inclusion

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#181]
Address the results of the conversation from #170  
- [ ] CCG will formally announce a meeting for PRs for VC Maintenance & VC Maint Chairs (@brentzundel & @wyc) will hold a meeting to discuss.

**Comment by vsnt** [comment]
fyi @wyc @brentzundel

**Comment by wyc** [comment]
Depends on #180

**Comment by brentzundel** [comment]
@wyc and myself will organize a meeting for the VCWG once there is a set of PRs that the editors feel should be added to the VC spec. As far as organizing CCG meetings for the VC maintenance work to work on those PRs, that would best be done by the VC spec editors.
As far as I'm aware, that list currently consists of @msporny.

**Comment by msporny** [comment]
> As far as I'm aware, that list currently consists of @msporny.

I expect that we won't be able to do this until the DID Core specification is in Candidate Recommendation phase... and we're clear of the VC HTTP API work that's being done right now. Unfortunately, end of March at the earliest. We could have a meeting to triage, but the group of people doing stuff on VCs/DIDs/etc. are currently engaged w/ higher priority items.

Also, need a supporting Editor for the VC spec -- we should spend some time finding someone (that will actively do work -- not just someone that wants their name on a spec). We might want to bring this up on a future CCG call.

Next steps seem to be:

1. Announce request for supporting Editor for VC spec.
2. Announce meeting to triage VC spec issues -- perhaps early March.
3. Announce working meeting to make active progress on VC issues -- late March.

**Comment by clehner** [comment]
I hope the VCWG can also address PRs on the VC Test Suite: https://github.com/w3c/vc-test-suite/pulls

**Comment by kimdhamilton** [comment]
4/20/21: Have PR coming soon.

**Comment by wyc** [comment]
https://github.com/w3c/vc-data-model/pull/774 <- PR being reviewed. Will share with list shortly.

**Comment by vsnt** [comment]
@wyc has scheduled this, so closing this item.
