### ISSUE TITLE
Publish notes from 2/17

### ISSUE THREAD

**Issue by wyc** [w3c-ccg/community#183]
Just a reminder for me, but anyone is free to do it! :)

**Comment by vsnt** [comment]
Here is a "how to" using the github interface: https://docs.google.com/document/d/1xsFZ6GKOHLsYwIN8DGYnVZRtxvx9eVZ4QQ6WJF6zgcI/edit

**Comment by vsnt** [comment]
@bumblefudge Juan, did you do these minutes in your minutes backlog? If so, let's close this item. cc @wyc FYSI+management

**Comment by bumblefudge** [comment]
It looks like the minutes were already cleaned and ready to go when I did my clean-up sweep BUT there was a group.txt file missing, so I've [PRd one in](https://github.com/w3c-ccg/meetings/pull/72).  Other than that, should be GTG?

**Comment by vsnt** [comment]
@bumblefudge there's a conflict in that PR, would you please take a look and update. Thanks

**Comment by TallTed** [comment]
@vsnt -- https://github.com/w3c-ccg/meetings/pull/72 appears to have been merged, so this can probably be closed.

**Comment by vsnt** [comment]
Complete. Thanks all.
