### ISSUE TITLE
[PROPOSED WORK ITEM] CHAPI Interoperability Test Suite

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/community#185]
# New Work Item Proposal

This is a new work item proposal for the test suite for the Credential Handler API. The proposed work item is here:

https://github.com/w3c-ccg/chapi-interop-test-suite

The Draft Credential Handler API specification is here:

https://w3c-ccg.github.io/credential-handler-api/

A polyfill implementation for CHAPI as well as test sites can be found here:

https://github.com/digitalbazaar/credential-handler-polyfill/

The draft CHAPI specification can be found here:

https://w3c-ccg.github.io/credential-handler-api/

## Abstract

The CHAPI Interoperability test suite is used to demonstrate issuer to holder to verifier interoperability using the Credential Handler API. The Credential Handler API was created to achieve the following goals:

#### Goal 1: Make using credentials easier and safer for people

Credential management is becoming fundamental to a new generation of web applications. People need the ability to safely store and manage credentials (from diplomas to coupons), and they need a consistent trusted UI (aka "trusted chrome" in industry parlance) to do that.

#### Goal 2: Give people ability to choose their wallet provider

Just as it's important for people to have choice of music players, web browsers, PDF viewers, and so on, it's crucial for them to be able to choose service providers for wallets and credential storage (with safeguards and sane defaults).

#### Goal 3: Give web app developers a standard wallet API

Web app developers should not be required to roll their own wallet  infrastructure for every application. Using a standard credential management API allows developers to:

* Minimize the risk of data leaks and identity theft
* Participate in the [Verifiable Credentials](https://w3c.github.io/vc-data-model/) ecosystem  

## Owners

The leads for this project are:

@gannan08 @kdenhartog

**Comment by TallTed** [comment]
It would be helpful to include a direct link to [the draft Credential Handler API spec](https://w3c-ccg.github.io/credential-handler-api/) in the opening paragraph.

**Comment by msporny** [comment]
> It would be helpful to include a direct link to [the draft Credential Handler API spec](https://w3c-ccg.github.io/credential-handler-api/) in the opening paragraph.

Done.

**Comment by vsnt** [comment]
Hi @msporny thanks for this. Can you address [these questions](https://w3c-ccg.github.io/workitem-process/#work-item-questions) & also identify if this supports/is related to the SVIP work in your Work Item Request. cc @gannan08 @kdenhartog  Thank you. 

- [ ] Explain what you are trying to do using no jargon or acronyms.
- [ ] How is it done today, and what are the limits of the current practice?
- [ ] What is new in your approach and why do you think it will be successful?
- [ ] How are you involving participants from multiple skill sets and global locations in this work item? (Skill sets: technical, design, product, marketing, anthropological, and UX. Global locations: the Americas, APAC, Europe, Middle East.)
- [ ] What actions are you taking to make this work item accessible to a non-technical audience?

**Comment by msporny** [comment]
> Hi @msporny thanks for this. Can you address [these questions](https://w3c-ccg.github.io/workitem-process/#work-item-questions)

Could we work these questions into the "New Work Item" template? I thought I had read the appropriate section in the new work item process, but totally missed these questions (which, upon reading them, remember that all new work items need to provide answers to them -- so thank you, @vsnt for pointing it out, totally overlooked them).

> Explain what you are trying to do using no jargon or acronyms.

This test suite is used to make sure that Verifiable Credential issuers, digital wallet providers, and Verifiable Credential verifiers that claim they are compatible with the Web-browser based Verifiable Credentials ecosystem can demonstrate that they are.

> * [ ]  How is it done today, and what are the limits of the current practice?

At present, implementers tend to click through the CHAPI demo sites and various other interoperability sites to see if they are conformant. This does not check corner cases, is a manual process, and does not provide an objective measure of conformance.

> * [ ]  What is new in your approach and why do you think it will be successful?

The new approach provides an automated process with objective tests that check for corner cases. A report is produced that can then be compared to other conformance test reports to see which implementers support which features.

> * [ ]  How are you involving participants from multiple skill sets and global locations in this work item? (Skill sets: technical, design, product, marketing, anthropological, and UX. Global locations: the Americas, APAC, Europe, Middle East.)

These tests are the result of the DHS Silicon Valley Interoperability Program InteropFest, which pulls in individuals from private industry, government (technology, privacy, specific business components), and the Credentials CG. The tests focus on real world use cases and involve people from US, Canadian, EU, and New Zealand backgrounds (to date). The purpose of the work item is to get broader engagement from CCG and W3C (which are global in nature and involve individuals from around the glob).

> * [ ]  What actions are you taking to make this work item accessible to a non-technical audience?

The output of the test results are provided in a human readable form. An example can be found here (warning 40MB file, long load times due to image capture at each step of the process):

https://w3c-ccg.github.io/chapi-interop-test-suite/docs/reports/report-2020-12-11T06:00:00+00:00.html

The output for each report is a human readable summary (green with checkmark good, red with X bad), and images that visually show the screen result of each test.

**Comment by vsnt** [comment]
Thanks @msporny. And yes, I know I need to update it in the work item template - that is something on my todo... 

It would be great to include these answers in the readme. The real reason for them is to make the work items more accessible to folks not directly working on them. :-)

**Comment by msporny** [comment]
>  I know I need to update it in the work item template - that is something on my todo.

One less item on your to do list. :)

Done here:

https://github.com/w3c-ccg/community/commit/b6f9ff9999040072bc7f275fd025e39a0696bb49

**Comment by vsnt** [comment]
@msporny I was just in there editing, LOL.

**Comment by msporny** [comment]
> It would be great to include these answers in the readme.

Good suggestion, done in https://github.com/w3c-ccg/chapi-interop-test-suite/commit/d481dccbcb0165b3a167caad268c549a5c757d0e

**Comment by vsnt** [comment]
@msporny does this work item request need a new repo or are we good to move forward and close this issue?

**Comment by msporny** [comment]
> @msporny does this work item request need a new repo or are we good to move forward and close this issue?

We don't need a new repo since we just transferred the Digital Bazaar repo to W3C CCG:

https://github.com/w3c-ccg/chapi-interop-test-suite/

We're in good shape wrt. this work item, everything has been setup and transferred.

We should close this issue.
