### ISSUE TITLE
CCG Co-Chair Role

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#196]
There is an open co-chair role. This needs to be filled in order to keep consistency in the community.

**Comment by vsnt** [comment]
Co-Chair job description: https://docs.google.com/document/d/18uPGjBw15i9jLRQ5K4SCwrrGU6zBIB3PpIap17X39fo/edit

**Comment by mprorock** [comment]
As noted on the mailing list - I have self nominated for this

**Comment by vsnt** [comment]
We have a new co-chair. Congrats @mprorock !
