### ISSUE TITLE
What's going on in the IFT?

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#197]
What's the status of IFT issues? https://github.com/w3c-ccg/infrastructure/issues

**Comment by vsnt** [comment]
@wyc is any work being done by the IFT? 

From the last update in June's no meetings had happened or were planned and nothing was being done. If you would like to keep the Infrastructure Task Force active, I formally ask for a status update per the Work Item Process (https://w3c-ccg.github.io/workitem-process/#work-item-target-deliverable-classification) and a plan for regular meetings and action plan to address current issues. If not submitted, I recommend all IFT assigned issues be moved back into the main CCG issues repo to track from there.

This request is to consolidate tracking issues so they can be addressed with minimal organization overhead.

cc @wyc @mprorock @msporny

**Comment by wyc** [comment]
Hi @vsnt, thanks for the formal request for a status update. The past several meetings have been occurring with no major technical issues, and we're proud of the outcome. That's all.

Due to the low overhead we aim to keep at IFT, meetings are ad hoc as the community needs them. The vast majority of the issues in the IFT are awaiting improvements in Jitsi upstream or recommended documentation. While it is nice to hold a completionist demeanor towards work, those issues will be addressed in their own time when volunteer community members have time to do so, and there have been no deadlines set. As per your implication that the active status of IFT is at risk, I would note that towns don't shut down their fire departments because there have been no recent fires.

**Comment by vsnt** [comment]
This request comes after reviewing the work item process (for another community question) which includes specific requirements for active task forces (https://w3c-ccg.github.io/workitem-process/).

@wyc you mention you have had meetings, would you please provide the minutes (including dates + who attended + topic) for these meetings and where they are posted online? I have not see notification of recent ITF meetings on the main CCG list, which is where all the other task forces and work item meetings are communicated along with their minutes, so I have been unaware of any of these meetings. Apologies if you have already done this, just send me the links to review.

In reviewing the IFT repo, I can not find much if any progress/completion since Feb. There are 12 open issues, none have been closed, and no changes have been made to the repo since the Feb 24 kickoff. I fail to see the value of keeping these issues managed separately where I can not see any progress in 6 months?

Many of the issues in the ITF originated in the CCG meetings repo and were moved to the IFT with the promise they would be better managed and completed in their own repo. Based on the github history+tracking, I'm just not seeing an improved management or completion of issues. Therefore, it is in the best interest of these items if they are moved back into the main CCG repo. Infrastructure issues were effectively managed and completed before the a separate task force was created, so I find your fire department argument unconvincing. If they can not be actively managed in the IFT, they need to be rolled up to the overall co-chairs, of which you continue to have oversight.

I'm curious to hear your thought on the best way forward to actively managing and completing these issues so they do not fall through the cracks or get forgotten in a buried repo as it seems they have for 6 months?

**Comment by wyc** [comment]
There have been two meetings since the kickoff, none as of late. Are you saying tasks forced and work items all require normal meeting times? That was not what was agreed to in the IFT. There have also been fewer critical issues needing immediate redress or non-upstream fixes, could you list a few active ones if you can recall? Thanks.

**Comment by vsnt** [comment]
Great! Can I see the minutes for those meetings?

**Comment by wyc** [comment]
The meetings are not for specification drafting or meant for IPR protection, we were mainly populating the issues you see now in the repo with that time, so I don’t know that notes are available. I would also object to the burdensome requirement of every community gathering producing notes especially in the early formative stages of a workstream without IPR protection as an objective. If you would like to require every single meeting among CCG members to produce notes and recordings, we could run it by the community.

**Comment by TallTed** [comment]
@wyc -- 

At the risk of speaking out of turn...

Meeting notes are required by TF charter, CG charter, WG charter, etc. Setting up pre-meeting agendas is recommended as well, as comparing those agendas to the minutes/notes helps show that the group is accomplishing its goals.

In the general case, meeting minutes aren't just for IPR. They're also helpful to bring new members of a subgroup up to speed; or for other interested super-group members to see the basis for decisions or other output of the subgroup, which may sometimes lead to new information or other resources being provided to that subgroup, which may lead to alteration of those decisions or other output; among other values.

For the immediate, putting rudimentary notes of what was discussed and/or accomplished in those informal meetings — perhaps a bit more detailed than what you have stated here — into the relevant directories would probably suffice. It would be helpful if you could include the names of all those present, but for this TF in particular, it's probably not necessary to have recordings or precise notes of who said what and when, to date.

**Comment by vsnt** [comment]
@wyc per @TallTed comment above. Could you please provide the rudimentary notes for the IFT meetings?

**Comment by vsnt** [comment]
Closing. ITF tasks have been rolled back into main CCG issues repo (this one).
