### ISSUE TITLE
Spec-Text Training

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#2]
Currently assigned to @msporny ?

**Comment by ChristopherA** [comment]
Still need docs on how to initialize repo.

**Comment by ChristopherA** [comment]
We are awaiting video upload @andrewhughes3000

**Comment by andrewhughes3000** [comment]
The raw recording is here: https://youtu.be/vcL3ffgGEJM
I'm still planning to edit this recording to chop out the dead air etc.

**Comment by andrewhughes3000** [comment]
Bohdan Andriyiv has saved me! He has edited the video, cutting out the irrelevant parts, and inserting title slides and an index.
I will load this up to Youtube and provide the URL.
Where should I load the mp4 file (760MB) for safe-keeping?

**Comment by andrewhughes3000** [comment]
The edited video tutorial on creating a ccg github repository and initialization of a new ReSpec file is here: https://youtu.be/0eQXU6Z-A6Q

**Comment by jandrieu** [comment]
Done!
