### ISSUE TITLE
Scribe Tool: Add drop down to select meeting 

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#203]
The current scribe tool (https://w3c-ccg.github.io/meetings/scribe-tool/) does not automagically pull minutes from all task force meetings (e.g. VC-EDU). The VC-EDU task force has begun using the CCG jitsi infrastructure for meetings and notes. 

Request: add drop down to the scribe tool to select which meeting you are pulling minutes from.

Workaround: pull the files directly from the templated URLs, e.g. but replace with the date to download the minutes.

<ccgbot> Raw transcript at
https://meet.w3c-ccg.org/archives/w3c-ccg-education-2021-07-19-irc.log
<ccgbot> Raw audio at
https://meet.w3c-ccg.org/archives/w3c-ccg-education-2021-07-19.ogg
<ccgbot> Raw video at
https://meet.w3c-ccg.org/archives/w3c-ccg-education-2021-07-19.mp4

**Comment by mprorock** [comment]
@vsnt thinking right near the fetch by date button?

**Comment by bumblefudge** [comment]
worth noting that vc-http-api and traceability both happen on Tuesdays... so it might be worth putting it to the LEFT of the fetch-by button!

**Comment by vsnt** [comment]
CCG 101 and the main CCG call also happen on Tuesdays. It's the CCG meeting day!

**Comment by wyc** [comment]
@mprorock says it's in progress.

**Comment by vsnt** [comment]
Completed with the 12/21 jitsi and minutes infrastructure work by @msporny. Closing this issue.
