### ISSUE TITLE
[PROPOSED WORK ITEM] Break out use-cases for VC-[HTTP-]API as distinct repo with Editors

### ISSUE THREAD

**Issue by bumblefudge** [w3c-ccg/community#207]
# New Work Item Proposal

vc-http-api use cases as a distinct repo/work-item 

## Include Link to Abstract or Draft 

Here's the working file the group has been using for weeks:
https://docs.google.com/document/d/1-u0_Ub6feiX6DH3jXFJFjt6n3CwKGpkmC3VISqDkWL4/edit#

## List Owners

Primary editor: Eric Schuh (Legendary Requirements), @eric-schuh
Secondary editor: Juan Caballero (Spruce Systems), @bumblefudge

## Work Item Questions

> Answer the following questions in order to document how you are meeting the requirements for a new work item at the W3C Credentials Community Group. Please note if this work item supports the Silicon Valley Innovation program or another government or private sector project.

1. Explain what you are trying to do using no jargon or acronyms.

Simply want the use-case documents to have a distinct respec repo and git history from the API's documents.

2. How is it done today, and what are the limits of the current practice?

The API working group's current documentation is limited to markdown files; building the use-case document could happen in the repo, but we feel that both weekly meetings and github-based discussions would both be clearer and easier for more people to track and participate in with the use-cases happening elsewhere in parallel.

3. What is new in your approach and why do you think it will be successful?

At the moment, not much! We're hoping to make a use-case document similar to the VC use-cases doc, and inherent some of the ReSpec JS tooling that autogenerated the tables and linked indexes.

4. How are you involving participants from multiple skill sets and global locations in this work item? (Skill sets: technical, design, product, marketing, anthropological, and UX. Global locations: the Americas, APAC, Europe, Middle East.)

We welcome inputs from the "business side of the house" to help us refine and iterate these use cases! 

5. What actions are you taking to make this work item accessible to a non-technical audience?

We can keep the google doc if it helps!

**Comment by vsnt** [comment]
Sounds like a great idea. Keeping it accessible via a google doc is important. You may also want to learn from the VC-EDU group on making use case work inclusive to folks not on github. @kayaelle & @kimdhamilton would probably have comments/suggest others to comment.

adding @mprorock as he is co-chair.

**Comment by mprorock** [comment]
+1 big approval from my side - @wyc any objections to getting this up?

**Comment by bumblefudge** [comment]
I did not tag Kim on purpose, but thanks for checking!  I think last time this happened TallTed pointed out some kind of repo-wide configuration or setting for default reviewers

**Comment by wyc** [comment]
No objections here, looks great! Good to see some new names contributing too.

**Comment by vsnt** [comment]
I have added this work item to the 9/21 CCG call agenda to review+discuss with the community. Would the owners please attend this meeting. Thank you. https://lists.w3.org/Archives/Public/public-credentials/2021Sep/0074.html

**Comment by vsnt** [comment]
Per discussion at the 9/21 CCG call, this work item has entered the 7 day review period. If anyone has concerns about this becoming a work item, it should be raised prior to EOD Sept 29, 2021. If no concerns are raised, this will move to a work item at that time.

**Comment by vsnt** [comment]
This repo has been transferred and is ready to go here: https://github.com/w3c-ccg/vc-api-use-cases.
