### ISSUE TITLE
Need update from Ethereum Community on differences on various DID-based EIPs

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#21]
@christianlundkvist can you find someone to help us with this?

**Comment by kimdhamilton** [comment]
I think we covered this last meeting; ok to close?

Reference: https://medium.com/uport/a-complete-list-of-uports-protocols-libraries-and-solutions-63e9b99b9fd6

**Comment by ChristopherA** [comment]
Not sure if we can close - it needs to be documented in CCG somewhere people can find it.

**Comment by peacekeeper** [comment]
@drabiv volunteered to take the lead on this, he was planning to explore Ethereum-based identity proposals this month anyway. I'm available to help if/when needed.

**Comment by ChristopherA** [comment]
I don't want this item to be closed until:

* [ ] Some documentation or links to this topic is in one of our repos, work items, or reports.
* [ ] Searchable and findable by the public and prospective CCG members.

**Comment by kimdhamilton** [comment]
I will ping @Drabiv to see if he still has plans to address. My personal opinion is that this isn't an action item for the CCG. While this documentation is useful generally, I don't think it needs to be a CCG requirement.

The only action item related to the CCG group would be adding any relevant DID methods to the DID method registry (and relevant documentation).

**Comment by Drabiv** [comment]
@ChristopherA @peacekeeper @kimdhamilton here's a summary of EIPs that use DID standards and closely related to them EIPs that use VCs for identity management. Please, let me know if and where it should be commited.  

@frozeman @oed @pelle @NoahZinsmeister feel free to edit the list, point to more info, especially wrt to the key differences of your EIPs.


## EIPs that use DID and VC standards


| EIP | Summary | Abstract | Comment |
| ------ | --- | --- | --- |
|  [EIP-725](https://github.com/ethereum/EIPs/issues/725)     | A standard interface for a simple proxy account (identity account). | The following describes standard functions for a unique identifiable proxy account to be used by humans, groups, organisations, objects and machines. The proxy has 2 abilities: (1) it can execute arbitrary contract calls, and (2) it can hold arbitrary data through a generic key/value store. One of these keys should hold the owner of the contract. The owner may be an address or a key manager contract for more complex management logic. Most importantly, this contract should be the reference point for a long-lasting identifiable profiles. | Author/promoter -  [ERC-725 Alliance](https://erc725alliance.org/) |
| [EIP-734](https://github.com/ethereum/EIPs/issues/734) | A contract for key management of a blockchain proxy account. | The following describes standard functions for a key manager to be used in conjunction with ERC725. This contract can hold keys to sign actions (transactions, documents, logins, access, etc), as well as execute instructions through an ERC 725 proxy account. |  Author/promoter - [ERC-725 Alliance](https://erc725alliance.org/) |
| [EIP-735](https://github.com/ethereum/EIPs/issues/735) | A standard for adding, removing and updating on-chain claims. | The following describes standard functions for adding, removing and holding of claims. These claims can attested from third parties (issuers) or self attested. |  Author/promoter -  [ERC-725 Alliance](https://erc725alliance.org/) |
| [EIP-780](https://github.com/ethereum/EIPs/issues/780) |  A proposal for Ethereum Claims Registry  to provide a central point of reference for on-chain claims on Ethereum. | This text describes a proposal for an Ethereum Claims Registry (ECR) which allows persons, smart contracts, and machines to issue claims about each other, as well as self issued claims. The registry provides a flexible approach for claims that makes no distinction between different types of Ethereum accounts. The goal of the registry is to provide a central point of reference for on-chain claims on Ethereum. | Author/promoter - [Consensys:Uport/3Box](https://labs.consensys.net/portfolio/) |
| [EIP-1056](https://github.com/ethereum/EIPs/issues/1056) | A registry for key and attribute management of lightweight blockchain identities. | This ERC describes a standard for creating and updating identities with a limited use of blockchain resources. An identity can have an unlimited number of delegates and attributes associated with it. Identity creation is as simple as creating a regular key pair ethereum account, which means that it's fee (no gas costs) and all ethereum accounts are valid identities. Furthermore this ERC is fully DID compliant. | Author/promoter - [Consensys:Uport/3Box](https://labs.consensys.net/portfolio/) |
| [EIP-1812](https://github.com/ethereum/EIPs/pull/1812) | Reuseable Verifiable Claims using EIP 712 Signed Typed Data. | A new method for Off-Chain Verifiable Claims built on EIP 712. These Claims can be issued by any user with a EIP 712 compatible web3 provider. Claims can be stored off chain and verified on-chain by Solidity Smart Contracts, State Channel Implementations or off-chain libraries. | Author/promoter - [Consensys:Uport/3Box](https://labs.consensys.net/portfolio/) |
| [EIP-1484](https://github.com/ethereum/EIPs/issues/1495) | A protocol for aggregating digital identity information that's broadly interoperable with existing, proposed, and hypothetical future digital identity standards. | This EIP proposes an identity management and aggregation framework on the Ethereum blockchain. It allows entities to claim an Identity via a singular Identity Registry smart contract, associate it with Ethereum addresses in a variety of meaningful ways, and use it to interact with smart contracts. This enables arbitrarily complex identity-related functionality. Notably (among other features) ERC-1484 Identities: are self-sovereign, can natively support ERC-725 and ERC-1056 identities, are DID compliant, and can be fully powered by meta-transactions. | Author/promoter - [Hydrogen](https://medium.com/hydrogen-api/examining-erc-1484-hydro-snowflake-cc3753a5ff52) |

**Comment by oed** [comment]
Thanks @Drabiv. Just want to point out that ERC 780 is no longer supported by Uport nor 3Box 🙂

**Comment by Drabiv** [comment]
@oed I thought so). If it is no longer supported, I'm removing ERC 780 from the list to avoid confusion.

**Comment by TallTed** [comment]
@Drabiv - Given that [every `Comment` here](https://github.com/w3c-ccg/community/issues/21#issuecomment-476170218) is an `Author/promoter`, I'd change that column header to `Author/promoter` and make the obvious value edits. If additional `Comment` is needed later, such a column can be added back...

**Comment by ChristopherA** [comment]
@Drabiv I think it is important to keep a row for ERC 780 and state it is no longer supported (or deprecated? Did anything ever use it?)

**Comment by Drabiv** [comment]
@TallTed I was thinking about this, the problem is that there's not enough space for additional column (it will create horizontal scroll bar). Also for new editor, it will be psychologically easier to add comment into the current comment column, rather than create new comment column. Hence naming this column "Comment" is better.

@ChristopherA readded EIP780 to the list. As it appears it can be still be used by ERC725 standard - https://github.com/ethereum/EIPs/pull/1867#issue-264289448

Just to be clear, I am not an expert on Ethereum based identity standards. It is difficult to comment on intricacies of different EIPs, especially as they actively change.  As I understand, currently there are 2 approaches being actively developed. One led by ERC725 foundation (EIP - 725 (darft2) and related 734, 735,780(?)) and one led by Uport - (EIP - 1056, 1812). Both of them are under active development. 

I hope the above table and this comment, will help to understand more about current Ethereum based identity standards, and motivate someone to update the above table or write an article to clarify the purpose of EIPs and the differences between them. 

Also, it makes sense to have one Ehtereum based identity standard - so hopefully having clear comparison between different approaches, will entice emergence/convergence of/to one standard.

**Comment by ChristopherA** [comment]
Thank you @Drabiv for pulling the list together. The chairs would really like to see some people from those communities explain the differences. @Drabiv can you investigate what the GitHub names of the key people are so we can tag them here is issues?

**Comment by frozeman** [comment]
Yeah 780 is still a valid claim registry, but i think it needs some work. please let it in there.
Many of those standards are experimental, but important to list.

**Comment by Drabiv** [comment]
> Thank you @Drabiv for pulling the list together. The chairs would really like to see some people from those communities explain the differences. @Drabiv can you investigate what the GitHub names of the key people are so we can tag them here is issues?

@ChristopherA, this is already done here - https://github.com/w3c-ccg/community/issues/21#issuecomment-476170218

**Comment by ChristopherA** [comment]
> this is already done here

@Drabiv I'm seeing links in that comment to the websites, but I'm seeking the github names, which allows us to tag them here.

**Comment by Drabiv** [comment]
@ChristopherA I see. I had them mentioned above the table. Now, added their GitHub names in the table also.

**Comment by kimdhamilton** [comment]
Thanks @Drabiv, this is great! I'll assign to myself to figure out where we want such documentation to go

**Comment by ChristopherA** [comment]
Were can we put @Drabiv's table to be a persistent place? Maybe move to be an #RWOT9 topic.

I'd like to see this issue closed.

**Comment by ChristopherA** [comment]
@Drabiv — Are all of these now in the DID Registry? Should we just close this item, or is this table useful somewhere else? Will close in 30 days if no response.

**Comment by Drabiv** [comment]
@ChristopherA sorry, I won't be able to help with this. I have not followed identity related EIPs for a long time and not sure what is the current state. Unfortunately, currently I have no time to research the topic to have a good enough understanding to comment.

**Comment by TallTed** [comment]
@ChristopherA - Was this intentionally closed? (You gave 30 day warning, but closed immediately without that wait...)

**Comment by jandrieu** [comment]
@TallTed It was closed because DID Methods (EIPs or otherwise) go in the DID Method Registry. Drabiv had been assigned and several EIP-based DID Methods are in fact, in the registry.

Do you know of others active methods that are still missing? If so, we can re-open and assign this to you so we get that taken care of.

**Comment by TallTed** [comment]
@jandrieu - I have no substantive contribution, only a concern about the immediate closure happening simultaneously with comment that "Will close in 30 days if no response". I think the closure timing and comment about such should be aligned.
