### ISSUE TITLE
Submit a TPAC Breakout Session

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#210]
The CCG community is invited to submit a breakout session. 

https://www.w3.org/wiki/TPAC/2021/SessionIdeas

**Comment by mprorock** [comment]
I think a CCG 101 / How to get started in the Credentials / Decentralized space would be a great Q&A session for a breakout.  We should discuss with broader community on the next call

**Comment by vsnt** [comment]
N/A closing item
