### ISSUE TITLE
Request: VC-EDU specific mailing list

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#213]
VC-EDU taskforce has requested a VC-EDU specific mailing list. @kayaelle can you add details to this request please. Thank you.

**Comment by kayaelle** [comment]
The VC-EDU mailing list will be used to discuss education and workforce credential verifiable credential use cases as well as education standards alignment with verifiable credentials. It's suggested that we have a separate email list for this purpose to further engage the education and workforce community to aid in understanding and adoption. 

Meeting agendas and meeting minutes will be posted to both this list as well as the main CCG mailing list. Announcements & threads on the CCG mailing list deemed pertinent by the VC-EDU co-chairs will be shared with the VC-EDU mailing list.  The same code of ethics will apply to the VC-EDU mailing list.

**Comment by kayaelle** [comment]
List is now active: https://lists.w3.org/Archives/Public/public-vc-edu/

CCG chairs & Kerri Lemoie are current maintainers.

**Comment by vsnt** [comment]
Request complete. Closing item.
