### ISSUE TITLE
Co-operative Credentials  - Sub-group and Topical Call - DRAFT

### ISSUE THREAD

**Issue by nmeyne** [w3c-ccg/community#215]
# New Work Item Proposal - Co-operative Credentials

See [W3C-CCG New Work Item Process](https://w3c-ccg.github.io/workitem-process/)

## Abstract

https://coopcreds.com/

## Owners
Nick Meyne - Resonate Co-operative - [nmeyne (Nick Meyne) . Github](https://github.com/nmeyne)  (lead for this proposal stage)
Angus McLeod - The Pavilion Co-Operative - [angusmcleod (Angus McLeod) . Github](https://github.com/angusmcleod)
Federico Piovesan - Fairbnb.coop - [Federicopvs (Federico Piovesan) . Github](https://github.com/Federicopvs)

## 1. What we are doing
We are a core consortium of three established co-operatives aiming to build an inter-cooperative ecosystem, based on common membership and resource exchanges between co-operatives. We plan to do this through a  "Co-operative Credential" for every co-operative member inside the ecosystem. An SSI "tell us once" approach' will enable further opportunities for reduced friction and privacy-respecting cross-selling between co-operatives.

We feel there is a need for an open, organising focus for agreeing VC technical standards across the co-operative sector that is both vendor neutral and focused on the unique needs and values of the co-operative movement. If approved, following the example of the Verifiable Credentials for Education Task Force, we would like to target the creation of a chartered task force activity at W3C.  This will include pursuing data model recommendations that will demonstrate alignment with the VC model, usage guidelines, and best practices.

The group will explore the use of verifiable credentials with:
1. other co-operatives globally, on co-operative use cases
2. other task forces which may share similar use-cases or challenges (VC-EDU)
3. W3C inter-operability activities that could engage the co-operative sector and movement
4. Ecosystem governance activities, including principles and ethics

## 2. How is it done today
Co-operatives often use de-facto commercial federated identity management systems from large scale providers and expensive IDP's which can result in high KYC costs or risks for co-operatives.  Commercial third parties sometimes do not share co-operative values in respect of data transparency (data brokerage behind the scenes), lack of control by users over their data and the proliferation of identifiers in the commercial marketplace.  Co-operatives will continue to use existing standards (oauth2) to increase convenience for users by negotiating bilateral single sign on, in an effort to improve 'portability' of credential information, but Community Credentials can add open standardisation of privacy-respecting digital credentials and the multilateral opportunity to build a web of trust relationships.

## 3. What is new
We believe that utility and usability at scale are the key tests of an SSI ecosystem.  Our initiative will bootstrap at some scale, launching to the existing membership bases of the founding co-operatives while inviting other co-operatives to adopt and work on inter-operability.

We believe that [co-operative principle #6 - "co-operation among co-operatives"](https://www.ica.coop/en/cooperatives/cooperative-identity) (Cooperative identity, values & principles | ICA) will enable us to make faster progress on common credential definitions, use cases and trust issues.  Co-ops are wired to collaborate; commercial enterprises, particularly large ones, are wired to compete.  We think that 'community' can serve well as an anchor of trust in any complex identity ecosystem and that  the democratic experience of the co-operative movement could bring innovative solutions to the technical governance 'stack'.

## 4. Diverse involvement - skills, locations, ethics, needs and demographics
We are a consortium of three ethically-motivated co-operatives, with a truly global membership (Americas, EU, APAC, Africa).   We believe we are well placed to seed standards-building and grow inter-operability rooted in the [co-operative principles](https://www.ica.coop/en/cooperatives/cooperative-identity).  We are working with global and national co-operative associations such as ICA and in particular [Platform.Coop](https://platform.coop/). Our three founding co-ops are beginning with a specific use-case that will bring together the domains of ethical and sustainable tourism, fair rewards in the music and arts community and open-source community software development. Our use-case is a small beginning, but we aim to shape a 'community credentials' product and standards set capable of use by the global 3 million co-operative organisations with 1.2 billion members in total.   We have applied for and won funding for our work with the Next Generation Internet European Self-Sovereign Identity Framework Lab ESSIF-Lab, Business Open Call 2 and are reaching out to other organisations (including other co-operatives) within the EU NGI community.

## 5. Accessibility to a non-technical audience
We have created a [landing site](https://coopcreds.com/), and private community focused on the product aspects of Co-operative Credentials. We are actively inviting relevant stakeholders to participate, and we’re canvasing their views on Co-operative Credentials via stakeholder surveys.  We engage widely with other co-operatives on social media, however the global co-operative membership has a greater proportion of financially, socially, educationally and politically disadvantaged members than the corresponding representation in the customer base of the global social platforms.  We know that 'show', rather than 'tell' works best for these communities and that we will need to work hard on inclusion and accessibility.

**Comment by vsnt** [comment]
@nmeyne would you and your co-leads be able to attend the Nov 2 call to explain this work item to the community and answer questions?

**Comment by nmeyne** [comment]
Yes, very happy to do so.  Thanks for the opportunity.  I'll check with the others Regards,Nick Meyne
-------- Original message --------From: vsnt ***@***.***> Date: 29/10/2021  23:08  (GMT+00:00) To: w3c-ccg/community ***@***.***> Cc: Nick Meyne ***@***.***>, Mention ***@***.***> Subject: Re: [w3c-ccg/community] Co-operative Credentials  - Sub-group and Topical Call - DRAFT (Issue #215) 
@nmeyne would you and your co-leads be able to attend the Nov 2 call to explain this work item to the community and answer questions?

**Comment by msporny** [comment]
Very supportive of this work item... wish I had time to participate in it more.

**Comment by vsnt** [comment]
Community is supportive of this work item. We will start the 7 day waiting period to allow anyone to comment. Once this has completed, this will be created as a work item.

**Comment by vsnt** [comment]
This is a supported work item. I will open a new repo in the next few days.

**Comment by matt-l-w** [comment]
@vsnt - did the repo get opened?

**Comment by vsnt** [comment]
@matt-l-w @nmeyne @ Federicopvs @angusmcleod

This repo has been created: https://github.com/w3c-ccg/Co-operative-Credentials

**Comment by vsnt** [comment]
Repo has been created, so I am closing this issue.
