### ISSUE TITLE
Community Jitsi improvement requests from the community

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#217]
Please add your requests to improve our jitsi system.

**Comment by TallTed** [comment]
Username tab-completion is not currently in Jitsi, but I logged it last week as [a Jitsi Meet feature request](https://github.com/jitsi/jitsi-meet/issues/10263).  It's gotten no attention thus far, but I'd guess that more people commenting +1 or similar would raise some flags....

**Comment by vsnt** [comment]
Here's the item for adding a drop down to the scribe menu. https://github.com/w3c-ccg/community/issues/203

**Comment by rxgrant** [comment]
Get it working in Google Chrome.

**Comment by msporny** [comment]
> Get it working in Google Chrome.

It did for years, and still does in some versions of Chrome on some platforms (e.g., works for me in Google Chrome and Chromium). HOWEVER, Google just released a breaking change on some platforms that requires us to upgrade to the latest version of jitsi. This upgrade is schedule over the holidays (next week or week after).

We have done a test of this upgrade and it seems to work for most people we've tested with (and we're tracking down why one or two people didn't work). It might be that the latest version of Chrome is broken and we'll need to wait for the next update.

In any case, we're on it.

**Comment by TallTed** [comment]
For those like @rxgrant who are having trouble with Jitsi in Chrome (or any other browser), it may be worth trying [the standalone Jitsi Meet wrapper app](https://github.com/jitsi/jitsi-meet-electron/releases), available for macOS, Windows, and Linux.

It does have some issues, such as recently starting to force updates on users (it silently downloads in background, alerts upon completion, and auto-applies the new version upon next launch; if anyone reading this has the chops to contribute to make this more user friendly, such a PR might get applied; current contributors have not been friendly to this request), but I've found it better than further overloading my own browsers (for instance, my Chrome now has 1959 open tabs).

**Comment by msporny** [comment]
> for instance, my Chrome now has 1959 open tabs

You win. Somebody hand this man a medal. Has The Guinness Book of Records been contacted yet? :P

**Comment by msporny** [comment]
> When I spoke out against Zoom and in favor of Jitsi in October of 2020, it was with the understanding that the systems are based on open source and the code we run in CCG can be made public, so that other public groups can get away from shite software.

Why do you think the system isn't based on open source and the code isn't available? All the code is available under a BSD license:

https://github.com/digitalbazaar/cgbot
https://github.com/w3c-ccg/meetings/tree/main/scribe-tool

It's that, plus a stable version of Jitsi. That's what we run for CCG, there is nothing proprietary in the stack at present and everyone has access to the code. That will change when we do transcriptions, as Google Transcribe seems to be the only workable option there and people are suggesting switching to Zoom to get transcriptions (which would then lock us into a completely proprietary solution).

 We limit access to the jitsi server to admins (for security purposes). If you'd like to be an admin of the Jitsi server, please make a request to the chairs to add you. I could certainly use the help in managing that system. I'm happy to show anyone that wants to manage that system how it is set up (it's not a complex system to manage... Jitsi was the hardest part to get working in a way that meets the needs of the CCG).

**Comment by rxgrant** [comment]
> Why do you think the system isn't based on open source and the code isn't available? 

I don't think that.  Do you mean why did I ask you to explain the system a bit better?  The reason I'm checking in is because you've got people dropping off the call for multiple weeks while there's supposedly an upgrade, and when I asked for links explaining the system without this extra prodding they didn't arrive.

Thanks for the explanation.  
I'm offering to help and will email the chairs.

**Comment by rxgrant** [comment]
@msporny I've reread my message and think I could have been more polite in asking what the situation was.  Thanks for your explanation.  I have emailed the chairs to ask for access to start some documentation and get an overview of the system administration skills required.

> The only request of you that I have is this: please don't become one of the people that says that they're going to help, is then taken through training, and then ends up not helping. That has happened multiple times, and while I always start the process off hopeful that people are going to put in the effort, it almost always doesn't pan out. 

Hopefully nobody regrets the documentation that has been achieved.  I am going to keep trying.
