### ISSUE TITLE
[PROPOSED WORK ITEM] Verifiable Driver's License Vocabulary

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/community#218]
# New Work Item Proposal

## Include Link to Abstract or Draft 

The purpose of this work item is to demonstrate a path to interoperability between the ISO-18013-5 Mobile Driver's License data model and the W3C Verifiable Credentials ecosystem. The technologies explored in this work item are experimental and meant to be complementary to ISO-18013-5 (mDL) and not a replacement of the standard. The output of the work item would be a Verifiable Driver's License Vocabulary and an interoperability report between issuers and verifiers for Verifiable Driver's License Credentials using the Verifiable Driver's License Vocabulary. This report is generated on a weekly basis.

http://w3id.org/vdl/interop-reports 
https://github.com/digitalbazaar/vdl-vocab

## List Owners

@msporny @tplooker @clehner

## Work Item Questions

> 1. Explain what you are trying to do using no jargon or acronyms.

We are trying to demonstrate that it is possible to express driving credentials in a way that is compatible with the ISO-18013-5 Mobile Driver's License standard in a forum that is open to everyone, patent, and royalty-free. We are trying to address concerns that there is not going to be fair competition in this particular marketplace.

> 2. How is it done today, and what are the limits of the current practice?

At present, the mDL standard is pay walled and the discussions and decisions made on the standard are not subject to public scrutiny. This technology will affect hundreds of millions of people when deployed around the world and it is currently not being developed in an open standards setting organization. There are a number of proprietary implementation and privacy concerns related to the current mDL standard and this work attempts to provide vetted privacy-preserving alternatives to the current "phone home" nature of the mDL standard.

> 3. What is new in your approach and why do you think it will be successful?

Our approach is to utilize the W3C Verifiable Credentials standard, privacy-preserving approaches to credential presentation and revocation, and an open and patent and royalty-free process that is accessible to the general public to get industry buy-in on a privacy-respectful path forward. This approach, which involves the general public, was used successfully to build the Web.

> 4. How are you involving participants from multiple skill sets and global locations in this work item? (Skill sets: technical, design, product, marketing, anthropological, and UX. Global locations: the Americas, APAC, Europe, Middle East.)

We are reaching out to individuals that were involved in the mDL work (local and national governments), individuals involved in privacy analysis that has been critical of the mDL techology (ACLU, EPIC), individuals that were involved in the creation of W3C Verifiable Credentials (VCWG, DIDWG, CCG), and will be making a broad call for participation in each of those groups.

> 5. What actions are you taking to make this work item accessible to a non-technical audience?

We plan to provide a set of presentations throughout the next year or two that attempt to distill the technology down into easily graspable compare/contrasts between the path mDL is currently on and the alternative that vDL could provide.

**Comment by PrivacyCDN** [comment]
Hi;

For the information of the WG, see the Kantara Initiative [Report on Privacy and Identity Considerations in mDL Ecosystems ](https://kantarainitiative.org/reports-recommendations/#). The data flows covered in the report are:
![PImDL-DFDs](https://user-images.githubusercontent.com/3459574/144093038-cabd753d-3b6e-461e-941d-5ca8d61d6bd7.png)

Similarly, there is a newly formed Work Group for Privacy Enhancing Mobile Credentials that you might be interested in at https://kantarainitiative.org/groups/pemc-wg/

**Comment by mprorock** [comment]
This looks excellent, and has all key criteria met from my side - big +1 DB & MATTR

**Comment by wyc** [comment]
+1 spruce

**Comment by vsnt** [comment]
Per the CCG work item process, we'll leave this open for a week from the last call when we discussed (1/11). If there is no objection by 1/18, the work item will be approved and the chairs will open a repo.

**Comment by OR13** [comment]
I am in favor of this, work, but can't spare cycles to help.

**Comment by vsnt** [comment]
@msporny is there a repo to transfer to move this to the CCG?

**Comment by msporny** [comment]
The appropriate repos have been moved: 

https://w3c-ccg.github.io/vdl-vocab/
https://w3c-ccg.github.io/vdl-test-suite/

This item can be closed.

**Comment by vsnt** [comment]
Thanks @msporny and @davidlehn . If it's ok, I will wait till Monday to create full CCG repos, so we can these as a learning opportunity for work item creation training.

**Comment by msporny** [comment]
> I will wait till Monday to create full CCG repos, so we can these as a learning opportunity for work item creation training.

No need to create full CCG repos? They already exist -- we transferred the repos from DB to CCG. That said, perhaps you mean that the Chairs have a process to add content to repos to make it clear that it's a CCG repo?

**Comment by vsnt** [comment]
Yes!

**Comment by vsnt** [comment]
These repos have been opened:
https://github.com/w3c-ccg/vdl-test-suite
https://github.com/w3c-ccg/vdl-vocab
