### ISSUE TITLE
Jitsi audio error on Firefox, unable to hear participants that join after

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#219]
Tracking this known error in case others experience it. Suggestion is to use a different browser (not Firefox).

Error reported by CCG participant:
I have had a glitch with Jitsi that I have now figured out. I consistently cannot hear anyone who joins the call after I do. If I leave and reconnect, then I can hear the person speaking. All other participants can still be heard when this happens. I am using Firefox 89.0.1 on Mac.

Error description
Yes, it's a known issue in Firefox, and unfortunately, their WebRTC team is having a hard time fixing bugs:

The whole sad story about Firefox support is here (issue covers 2 years of
support requests for broken Firefox stuff):

https://github.com/jitsi/jitsi-meet/issues/4758

**Comment by vsnt** [comment]
@msporny did this get fixed with the 12/21 update?

**Comment by msporny** [comment]
> @msporny did this get fixed with the 12/21 update?

It did, and I have a lead on the new Chrome 97 bug -- stale session ID in local storage. The folks at our company have been able to get Chrome 97 and any version of Firefox that was failing by just clearing the local storage for the Jitsi site. 

I'll send this info out to the mailing list.

I think we can safely close this issue.

**Comment by vsnt** [comment]
@msporny thanks for the update. I will close this issue then. Again, thank's for your diligence on the CCG infrastructure.
