### ISSUE TITLE
BTCR Hackathon July 16th Planning

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#22]
We need to schedule a call for planning/allocating resources for the July 16th hackathon and daily standup. @ChristopherA @jandrieu @kimdhamilton @ben @rxgrant @danpape.

We also need some support that week on JSON-LD 1.1 issues: @dlongley (who else, Benjamin Young?)

+Kulpreet Singh, who is working on a Golang implementation

**Comment by kimdhamilton** [comment]
Sent poll https://doodle.com/poll/wvyhud57n6b7zer6

**Comment by ChristopherA** [comment]
@danpape, we'd love your advice!

**Comment by kimdhamilton** [comment]
Hackathon complete!
