### ISSUE TITLE
JSON-LD Signatures hosting

### ISSUE THREAD

**Issue by wyc** [w3c-ccg/community#221]
As per https://github.com/w3c-ccg/community/issues/97 we should figure out the hosting of JSON-LD schemas.

@ChristopherA 's original issue:

> There are a number of planned JSON-LD documents (that are not Verifiable Credentials) that plan to sign the documents with JSON-LD Signatures. These include some DIDs, revoked key lists, and other JSON-LD. However, there is no independent schema for JSON-LD Signatures. This schema could be subtracted from Verified Credentials scheme and should be be hosted somewhere in the CCG until a JSON-LD Signature WG takes it on toward a standard.
> 
> Ideally there should also be some functioning examples and pointers to reference code so that implementors can test their signing against the current specification.
> 
> This is also related to the task of archiving/closing out the DVCG in 2019 and moving any living specifications to new homes.
> 
>  Reliable URL people can start using to add to `@context` to support JSON-LD Signatures
>  Test examples of various valid signed JSON-LD documents
>  Links to various library and reference code (for instance I'd love to see JSON-LD signing playground updated to current standard)
>  Update JSON-LD Signature spec in CCG, and move/archive https://github.com/w3c-dvcg/ld-signatures out
> -- Christopher Allen
> 

Particularly useful is @OR13's comment https://github.com/w3c-ccg/community/issues/97#issuecomment-682615264

I've pasted it here:

> @vsnt please include all CODEOWNERS in any ccg repo that supports JSON-LD in that list, and maybe the list of repos as well... off the top of my head, they are:
> 
> https://github.com/w3c-ccg/security-vocab
> https://github.com/w3c-ccg/did-method-key
> https://github.com/w3c-ccg/lds-jws2020
> https://github.com/w3c-ccg/lds-ecdsa-secp256k1-2019
> https://github.com/w3c-ccg/did-method-web
> https://github.com/w3c-ccg/ldp-bbs2020
> https://github.com/w3c-ccg/vc-http-api
> https://github.com/w3c-ccg/did-resolution
> https://github.com/w3c-ccg/vc-examples
> https://github.com/w3c-ccg/vp-request-spec
> https://github.com/w3c-ccg/zcap-ld
> https://github.com/w3c-ccg/webkms
> https://github.com/w3c-ccg/ld-cryptosuite-registry
> https://github.com/w3c-ccg/universal-wallet-interop-spec
> https://github.com/w3c-ccg/ld-proofs
> https://github.com/w3c-ccg/did-method-v1
> We have a lot of people in this community who could support JSON-LD better, by relying on Digital Bazaar for everything JSON-LD we are risking creating an environment of learned helplessness :)
> 
> The more often someone a little less sure of themselves can solve a problem for the community, the stronger the support network grows.
> 

Related to: w3c-ccg/infrastructure#5

**Comment by vsnt** [comment]
Closing until there is sufficient interest to move forward. This can always be re-opened.
