### ISSUE TITLE
Consider upgrades to the teleconf system

### ISSUE THREAD

**Issue by wyc** [w3c-ccg/community#223]
- Auto present+ using Jitsi joins by adding those events to the script
- Auto publication of minutes, possibly delayed by 24 hrs
- Auto transcription services, such as Google translate. Investigate issues of privacy, quality of notes, community cohesion, etc.? Maybe a scribe can correct the machine-generated notes. Possibly even scribe to a Google doc.
- Explore translation of the minutes to other languages.

**Comment by vsnt** [comment]
Closing due to being address in 12/21 Jitsi upgrade by @msporny.
