### ISSUE TITLE
[PROPOSED WORK ITEM] Verifiable Credential Refresh 2021

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/community#226]
# New Work Item Proposal

Verifiable Credential Refresh 2021

## Include Link to Abstract or Draft 

https://digitalbazaar.github.io/vc-refresh-2021/#abstract

## Owners

@msporny, @mprorock 

## Work Item Questions

This work item supports the Silicon Valley Innovation program.

> 1. Explain what you are trying to do using no jargon or acronyms.

Verifiable Credentials can expire. It is useful to provide instructions on refreshing the credential for the times when expiration is imminent or has already occurred. The refresh can be performed manually or, with the prior consent of the credential holder, automatically. This specification details manual and automatic refresh mechanisms that Verifiable Credential issuers can utilize to enhance the experience when using their credentials.

> 2. How is it done today, and what are the limits of the current practice?

There is no mechanism to refresh a Verifiable Credential before it expires. Getting a new Verifiable Credential effectively requires a manual process that is similar to getting the Verifiable Credential for the first time.

> 3. What is new in your approach and why do you think it will be successful?

This approach builds on utilizing other CCG work items such as the VC API and the Verifiable Presentation Request specification to manually, or automatically, renew a Verifiable Credential that is getting ready to expire. This mechanism is expected to be broadly used by both the USCIS Permanent Resident Card (personal identification) program as well as the National Association of Convenience Stores TruAge program (age verification).

> 4. How are you involving participants from multiple skill sets and global locations in this work item? (Skill sets: technical, design, product, marketing, anthropological, and UX. Global locations: the Americas, APAC, Europe, Middle East.)

Other than the technical community, we are performing field testing with non-technical individuals in the retail sector, have been engaging legal counsel that specialize in privacy both in private industry and in federal government, digital wallet providers in the retail sector, and UX specialists  in both the US and Canada to ensure that the solution is both easy to use, meets regulatory burden, and is complaint with a number of US, Canadian, and European regulation.

> 5. What actions are you taking to make this work item accessible to a non-technical audience?

We are engaging with the CCG and a variety of non-CCG entites listed above. This has resulted in the need to engage with marketing, UX, and legal disciplines that are non-technical in nature. These interactions will eventually result in "plain english" explanations of how Verifiable Credentials using this specification are refreshed in a privacy preserving manner.

**Comment by vsnt** [comment]
@msporny We can discuss at the 1/18 CCG call. How much time do you want to go over this?

**Comment by msporny** [comment]
> @msporny We can discuss at the 1/18 CCG call. How much time do you want to go over this?

I can cover it in 5 minutes... or fill whatever time block you feel is appropriate, up to 30 minutes.

**Comment by vsnt** [comment]
@msporny great. We don't have anything else on the agenda, so if it's ok with you, I'll give you the whole time.

**Comment by mprorock** [comment]
per last meeting there are no objections into this.  @vsnt i suggest we approve and queue to move into ccg github on next batch

**Comment by vsnt** [comment]
@msporny is there a repo to transfer to move this to the CCG? Can you begin to transfer it to the CCG and we can set up the repo.

**Comment by msporny** [comment]
> @msporny is there a repo to transfer to move this to the CCG? Can you begin to transfer it to the CCG and we can set up the repo.

Yes, there is, and yes, I can do that.

**Comment by vsnt** [comment]
@msporny Did this repo get transfered? Thanks.

**Comment by vsnt** [comment]
This repo has been updated with the appropriate CCG files. Thanks. Closing issue.
