### ISSUE TITLE
Opencreds.org Update, Moves & Redirects

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#23]
The https://opencreds.org website and github needs to be updated, or content moved to the current site (or even become a new work item), or redirected to a more current document.

In particular
* https://opencreds.org/minutes/ refers to old meeting times
* https://opencreds.org/specs/ refers to old specs
* https://opencreds.org/specs/source/vision/ document was recently cited and maybe should be moved to http://w3c-ccg.github.io as a historical document. Or maybe it should be updated as a new CCG work item.
* https://opencreds.org/specs/source/glossary/ This is outdated, but may be worthy of a new CCG working
* https://opencreds.org/specs/source/use-cases/ needs to be redirected to the currrent WG doc
* https://opencreds.org/specs/source/identity-credentials/ is outdated, but maybe should be moved to CCG as a historical document (and a redirect).

@msporny @dlongley

**Comment by kimdhamilton** [comment]
Done
