### ISSUE TITLE
Update chairs on minutes, etc

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/community#230]
Need to rotate chairs names on minutes, etc. @msporny do you know where we change minutes template boilerplate with the chairs names? Thanks

**Comment by msporny** [comment]
Yes, here: https://github.com/w3c-ccg/meetings/blob/main/scribe-tool/config.js

... and done: https://github.com/w3c-ccg/meetings/commit/0b546183bfc08f61e32e24e4cb0ddec2e68bc727

**Comment by vsnt** [comment]
Thanks @msporny ! Closing issue.
