### ISSUE TITLE
[PROPOSED WORK ITEM] Public credential roadmap

### ISSUE THREAD

**Issue by vongohren** [w3c-ccg/community#231]
# New Work Item Proposal

See [W3C-CCG New Work Item Process](https://w3c-ccg.github.io/workitem-process/)

## Include Link to Abstract or Draft 

https://docs.google.com/document/d/14p9a5tk8IncNv_UXAkdLe3zT-k4a2FxZ1kQkDYf0LFM/edit?usp=sharing

## List Owners

@vongohren
Kimberly based on email thread.

## Work Item Questions

> Answer the following questions in order to document how you are meeting the requirements for a new work item at the W3C Credentials Community Group. Please note if this work item supports the Silicon Valley Innovation program or another government or private sector project.

1. Explain what you are trying to do using no jargon or acronyms.
Have a public roadmap kept up to date and make sure that the overall community is able to participate.

2. How is it done today, and what are the limits of the current practice?
Manu updates and make this available for discussion via email.
Manu also created this: https://github.com/w3c-ccg/vds-roadmap/blob/main/README.md, but we should define it to a work item

3. What is new in your approach and why do you think it will be successful?
Have a repo which holds  mermaid JS syntax and renders to a visual roadmap.

4. How are you involving participants from multiple skill sets and global locations in this work item? (Skill sets: technical, design, product, marketing, anthropological, and UX. Global locations: the Americas, APAC, Europe, Middle East.)
Everyone can create issues and participate and discuss why it should be on the roadmap

6. What actions are you taking to make this work item accessible to a non-technical audience?
Share on email, and also on DIF interoperability page and work group

**Comment by kwlinson** [comment]
Hi there @vongohren. Do we want to close this issue for now? 
Thanks,
Kimberly

**Comment by vongohren** [comment]
I believe so, I think I made it for someone else

**Comment by wip-abramson** [comment]
Closing this issue as per comments above. Although noting that having a roadmap for the CCG sounds like a good idea
