### ISSUE TITLE
[PROPOSED WORK ITEM] DID Resolution test suite

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/community#233]
# New Work Item Proposal

A test suite for DID Resolution.

## Include Link to Abstract or Draft 

- Github repo: https://github.com/danubetech/did-resolution-test-suite
- Example test report: https://danubetech.github.io/did-resolution-test-suite/gh-pages/2022-09-05_00:41:52/mochareports/reports.html

## List Owners

- @zaida-rivai
- @peacekeeper 

## Work Item Questions

> Answer the following questions in order to document how you are meeting the requirements for a new work item at the W3C Credentials Community Group. Please note if this work item supports the Silicon Valley Innovation program or another government or private sector project.

1. Explain what you are trying to do using no jargon or acronyms.

The CCG has a strong track record of working on various test suites, which has always been useful to the decentralized identity community.

In this case, we would like to contribute a test suite for DID Resolution:
https://github.com/danubetech/did-resolution-test-suite

This test suite can test various features of a DID resolver, and it is configurable to enable/disable certain sets of tests, as well as certain DID methods. It is not dependent on any single DID method. It tests DID Resolution in general, not any specific DID method.

In other words, the intention is to test the DID Resolution specification, which is already a CCG work item:
https://w3c-ccg.github.io/did-resolution/

2. How is it done today, and what are the limits of the current practice?

Today, DID Resolution is already implemented by many projects and libraries, such as the [DIF Universal Resolver](https://dev.uniresolver.io/), but there is no coordinated effort to make sure that implementations of DID Resolution are interoperable. Even though there is also a DID test suite, that focused mostly on the DID Core data model and omits the DID Resolution process. A DID Resolution test suite therefore complements current implementation and testing efforts.

3. What is new in your approach and why do you think it will be successful?

This is the first dedicated test suite that focuses specifically on DID Resolution, and we think it's an important step to increase interoperability on the DID layer of decentralized identity implementations. We invite implementers of DID resolvers to use and contribute to this test suite.

4. How are you involving participants from multiple skill sets and global locations in this work item? (Skill sets: technical, design, product, marketing, anthropological, and UX. Global locations: the Americas, APAC, Europe, Middle East.)

Danube Tech is very diverse company, and we have also involved other organizations in this work, including e.g. participants of the Silicon Valley Innovation Program. We hope that by contributing this as a CCG work items, we will get additional contributions from the wider community. We will also promote this through other community organizations such as DIF.

5. What actions are you taking to make this work item accessible to a non-technical audience?

This is primarily intended for a technical audience, but will also include test reports that can demonstrate interoperability of DID Resolution in an accessible way, e.g. see:
https://danubetech.github.io/did-resolution-test-suite/gh-pages/2022-09-05_00:41:52/mochareports/reports.html

**Comment by msporny** [comment]
+1 to this work item. It'll be fundamental to DID Resolution standardization and/or DID Method tests.

**Comment by mprorock** [comment]
The chairs held a proposal to adopt this work item, and we will begin the repo transfer process

**Comment by mprorock** [comment]
@peacekeeper - yep you can just transfer to w3c-ccg and ill accept

**Comment by peacekeeper** [comment]
@mprorock Done, thanks, I think we can close this!

**Comment by peacekeeper** [comment]
@mprorock Maybe before closing, can you add my account @peacekeeper as Admin to that new repo?

https://github.com/w3c-ccg/did-resolution-test-suite

**Comment by kwlinson** [comment]
Just cleaning up the work item list. Let us know if you need anything else with this. Thanks.
