### ISSUE TITLE
Create final report for RDF Dataset Canonicalization spec

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/community#234]
The "RDF Dataset Canonicalization" specification is currently a Draft Community Group Report:
https://w3c-ccg.github.io/rdf-dataset-canonicalization/spec/

There is a process through which a community group can publish a "final report", see here:
https://www.w3.org/community/about/faq/#how-do-we-publish-a-report

It would be great if this can be done for this work item, so that the new [RDF Dataset Canonicalization and Hash Working Group](https://www.w3.org/groups/wg/rch) can consider the CCG's final report as an input document.

**Comment by peacekeeper** [comment]
I created the necessary PRs to publish this as a Final Community Group Report:
- https://github.com/w3c-ccg/rdf-dataset-canonicalization/pull/30
- https://github.com/w3c/cg-reports/pull/15

**Comment by msporny** [comment]
This was done some time ago, Chairs can we close this issue?

**Comment by wip-abramson** [comment]
Closing this, as per @msporny comment above.
