### ISSUE TITLE
please enable github wiki functionality for this (and other relevant) repo(s)

### ISSUE THREAD

**Issue by TallTed** [w3c-ccg/community#240]
As commented during [today's call](https://www.w3.org/events/meetings/80a1023e-569b-4714-8fab-d1b84f2c3478/20230103T120000) — 

> I suggest we enable the wiki functionality on relevant repos, such that things like the charters that are being developed for the work items discussed today can actually be addressed in a place that we can all contribute to, and which is obviously visible and tracked more than something like a Google doc, which I think is where they are right now...

**Comment by mprorock** [comment]
seems extremely sane - thanks for bringing this up

**Comment by mprorock** [comment]
This should be up [here](https://github.com/w3c-ccg/community/wiki) @TallTed can you verify?

**Comment by TallTed** [comment]
Confirmed.  https://github.com/w3c-ccg/community/wiki is live.
