### ISSUE TITLE
[PROPOSED WORK ITEM] Test Suite for Verifiable Credentials v2.0

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/community#241]
## Abstract

The [Verifiable Credentials v2.0 test suite](https://github.com/digitalbazaar/vc-data-model-2-test-suite) provides a mechanism to test if an issuer or verifier is conformant with the Verifiable Credentials v2.0 data model. 

## Owners

@clehner @msporny (same organization, looking for a supporter from another organization)

## Work Item Questions

> 1. Explain what you are trying to do using no jargon or acronyms.

We are trying to create a mechanism that an implementer of the Verifiable Credentials v2.0 data model can use to determine if they are conformant with the [Verifiable Credentials v2.0 specification](https://www.w3.org/TR/vc-data-model-2.0/).

2. How is it done today, and what are the limits of the current practice?

At present, there is no test suite for the Verifiable Credentials v2.0 data model.

The Verifiable Credentials v1.1 data model required a number of things that made testing not as good as it could be, namely:

* It required implementers to create their own test infrastructure to run against the test suite.
* Implementers would often run the test suite once, and then not test again, resulting in implementations deviating from the specification without knowing that they were deviating.
* Updating the test suite was a laborious affair because test authors couldn't easily check to see if the test they were writing would break the ecosystem or not.

3. What is new in your approach and why do you think it will be successful?

The current approach utilizes the [Verifiable Credentials API](https://w3c-ccg.github.io/vc-api/) to provide a unified interface for issuing and verifying a Verifiable Credential. This approach has the following advantages:

* It allows implementers to use a common, well defined API to integrate into the test suite.
* It enables the test suite to be run against implementations on a regular basis.
* It enables test authors to easily test to see if new tests break the ecosystem or not.

We believe this approach will be successful because it has already been used to demonstrate interoperability among 13+ implementers in the Jobs for the Future Plugfest. That is, we already have 13 implementers that can integrate with this test suite.

> 5. How are you involving participants from multiple skill sets and global locations in this work item? (Skill sets: technical, design, product, marketing, anthropological, and UX. Global locations: the Americas, APAC, Europe, Middle East.)

This work item is highly technical in nature and executes upon the decisions made in the Verifiable Credentials v2.0 work, which has been demonstrated to be more broadly inclusive of different input from a variety of parties from around the world. 

Given that this is a test suite, it's audience are implementers and not necessarily people involved in design, product, marketing, anthropological, and UX fields. 

> 6. What actions are you taking to make this work item accessible to a non-technical audience?

We are generating a human-readable report as a part of the test suite output with easy to read columns stating which implementations pass vs. fail certain tests. The report should be citable/referenceable by non-technical individuals to understand how interoperability in the ecosystem is doing from a week-to-week basis.

**Comment by OR13** [comment]
I don't believe the `vc-api` (a CCG work item) should be required to demonstrate conformance to the vc data model 2.0 (a W3C VCWG work item).

**Comment by msporny** [comment]
> I don't believe the `vc-api` (a CCG work item) should be required to demonstrate conformance to the vc data model 2.0 (a W3C VCWG work item).

A couple of things to consider:

1. This doesn't have to be the only way to test against the core data model, other implementers can create alternative mechanisms to test conformance.
2. If we don't re-use just two endpoints of the VC API to drive this test suite, which already has 19+ implementers that integrate with it, a new bespoke mechanism will have to be proposed and created, generating even more work for an already overloaded WG with a solution that won't be reusable outside of this specification.

That said, if others would like to propose alternatives, the CCG Process allows for this. In the meantime, there are a large body of implementers that exist today that will be able to integrate with this test suite to demonstrate interoperability on the v2.0 VC data model.

**Comment by msporny** [comment]
> ```
> Copyright (c) 2022 Digital Bazaar, Inc. All rights reserved.
> ```
> 
> I think we will need this as a permissive license, etc to adopt.

Yes, agreed, we'll have to fix that -- the license is here and hopefully clarifies that the entirety of the test suite is under a W3C docs and code license:

https://github.com/digitalbazaar/vc-data-model-2-test-suite#license

**Comment by mprorock** [comment]
> I don't believe the `vc-api` (a CCG work item) should be required to demonstrate conformance to the vc data model 2.0 (a W3C VCWG work item).

Chair hat off:
If we are going to use an API for any testing, I would strongly prefer postman/newman based tests

**Comment by dlongley** [comment]
@OR13,

> I don't believe the `vc-api` (a CCG work item) should be required to demonstrate conformance to the vc data model 2.0 (a W3C VCWG work item).

I completely agree -- but I don't think that's being proposed here. This is just one possible test suite that can be used to demonstrate implementation of the VCWG 2.0 data model. It's just reusing work that people are already using elsewhere to help demonstrate interop. Of course, everyone should be welcome to create their own test suites that people could also / alternatively implement against.

**Comment by decentralgabe** [comment]
supportive of this work item. agree that vc-api shouldn't be a hard requirement, but an option. also against companies needing to host infrastructure to participate.

**Comment by msporny** [comment]
> supportive of this work item. agree that vc-api shouldn't be a hard requirement, but an option. also against companies needing to host infrastructure to participate.

I'll note that the following functions of the test suite are abstracted: issue(doc), verify(doc), prove(doc), verifyVp(doc)

https://github.com/digitalbazaar/vc-data-model-2-test-suite/blob/main/tests/10-vcdm2.js#L159-L162

... and the great thing about abstractions is you can use alternative mechanisms to issue/verify. So, if someone wants to do that through a command line interface to a docker instance (because they don't want to stand up infrastructure to run against the test suite), that can be done... if someone wants to do that via OIDC4 (because they prefer that protocol), they can... and if someone wants to do that via newman/postman, that's also possible (as long as people are willing to do the work).

**Comment by mkhraisha** [comment]
Supportive of this work item, and direction taken

**Comment by wip-abramson** [comment]
Update on this work item? I believe it is an active work item now right?

**Comment by msporny** [comment]
> Update on this work item? I believe it is an active work item now right?

Yes, and already migrated to W3C: https://github.com/w3c/vc-data-model-2.0-test-suite

This issue should be closed (as completed).

**Comment by wip-abramson** [comment]
Great
