### ISSUE TITLE
The CCG web pages needs work

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#242]
* [ ] The GitHub static home page https://w3c-ccg.github.io doesn't have a link to the list of topics for upcoming general meetings.
  * [x] It looks like that page might be https://www.w3.org/groups/cg/credentials/calendar — is that correct?
  * [ ] Is this page misnamed?
* [ ] The Roadmap is outdated and probably removed
  * [ ] Is there a more current one, or should it just be removed entirely
* [ ] IRC is mentioned as require, but the Jitsi chat framework does that for us.
   * [ ] Remove old references to using IRC web tools for meetings
   * [ ] Update for what people should know in Jitsi.
* [ ] The W3C page https://www.w3.org/community/credentials/ should be used minimally, as chairs can do limited editing there, and instead people should be referred to the GitHub static page.
  * [ ] Do the current chairs have access, and do they know how to edit the W3C.org page?
* [x] The new [Tasklist beta in GitHub](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists) makes issue management with subtasks so much easier. @ChristopherA has added us the waiting list. 
  * [ ] Waiting for GitHub to enable this, then add ` \`\```[tasklist] ` to top to make it use new UX.

**Comment by man4prez** [comment]
W3C CCG co-chairs don't have access to edit the [W3C CCG homepage](https://www.w3.org/community/credentials/), so we will have to work with the W3C staff to change/update the page.  

Yes, we are maintaining the list of upcoming meetings here:  https://www.w3.org/groups/cg/credentials/calendar

**Comment by ChristopherA** [comment]
Three different problems here.

a) the page I referred to is GitHub-static one https://w3c-ccg.github.io, which I've always felt was the "real" home page. The chairs should have access.
b) The W3C page should be somewhat editable by the chairs, if they are listed as chairs in the official W3C members list for the CCG. My advice has always been use that page as little as possible, and only refer to the GitHub home page.
c) The old chairs should have set via the W3C membership interface the new chairs. Did they?

**Comment by ChristopherA** [comment]
I show that the official w3c membership page https://www.w3.org/community/credentials/participants has the members at the top of this list as chairs:
<img width="678" alt="Screenshot 2023-03-07 at 2 00 37 PM" src="https://user-images.githubusercontent.com/69103/223563337-d04841dc-218b-49ba-87e1-9bcccd046ac3.png">

All should be able to log in and make changes to the CCG pages there. Though my advice is to delete everything you can and not use it other than to point to the GitHub pages, and for official business with W3C such as officially approved Final and Draft reports.

**Comment by man4prez** [comment]
We've worked with the W3C staff to update our WordPress page (https://www.w3.org/community/credentials/) as much as possible.  Since we don't update our WordPress page often (the co-chairs don't have the edit access), we hid most of the information and link out to our Github page (https://github.com/w3c-ccg) and W3C calendar (https://www.w3.org/groups/cg/credentials/calendar/) as much as possible.
