### ISSUE TITLE
Correct 'the the' in did-wg-charter

### ISSUE THREAD

**Issue by ken-ebert** [w3c-ccg/community#31]
In the document https://w3c-ccg.github.io/did-wg-charter/
Section 1 Scope

Change:
"Recommend a way of authoring specifications for DID Methods and protocols that are conformant with the the data model and syntax(es)."
to:
"Recommend a way of authoring specifications for DID Methods and protocols that are conformant with the data model and syntax(es)."

**Comment by msporny** [comment]
Fixed in https://github.com/w3c-ccg/did-wg-charter/commit/e8fcdd142d3ec16c75f47856307df5113a822b9d.
