### ISSUE TITLE
Create DID Explainer for W3C Tag, Integrate into DID Primer

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#38]
The [W3C Technology Architecture Group (TAG)](https://www.w3.org/2001/tag/) which reviews our proposals for working groups, has not found our current [DID Primer](https://w3c-ccg.github.io/did-primer/) satisfactory. They would like us to follow the template called an [Explainer](https://github.com/w3ctag/w3ctag.github.io/blob/master/explainers.md).

The W3C TAG said:
> * We found ourselves struggling to work out what use cases you are trying to support. What is the user need? When would I need a DID, and what would I do with it? It would be useful for our review if you would produce an explainer. (We've produced a template, which might be useful).
We didn't find those answers in your primer, since it starts from the explanation of what a DID is. We would really like to understand the need from a user's perspective, which already exists in daily life, written in clear non-technical language.

> * Also, does the group have or anticipate a mechanism for interoperability with current content loading? What relationship to HTTP do you envision? The question of whether DIDs are actually compatible with the web may be different depending on how they interact with HTTP. And if I were type a DID into a browser, application or user agent -- what would happen?

* [ ] We are current collaboratively drafting this document in Google Docs at https://docs.google.com/document/d/1JIWWs8YTWP83Hao5UXyrgpddYu9F0v8lGDUo0Usor10/edit This is the topic of our next meeting on December 4th.

* [ ] We need to evaluate this doc against the stories of experience in teaching about DID in the past, common questions, pain points, as we collated here:  https://docs.google.com/document/d/11sEvUhivMBt7DXBviqyEydvsnpOJY31O7KKw73eFdmc/edit

* [ ] We should get some validation of the final explainer by an outsider.

* [ ] Send final document to TAG.

* [ ] Turn over to DID Primer work item authors to integrate into final DID Primer to public as a CG Report.

**Comment by ChristopherA** [comment]
@manu reports we need this done by mid-January, somewhat because W3C Strong Auth & Identity Workshop report will be out, and there should be a link there.

**Comment by kimdhamilton** [comment]
to discuss 10/29:
Are we done? Need to turn over to DID WG? Wrap up?

**Comment by ChristopherA** [comment]
Does this move over to DID-WG?

Check with DID chairs.

**Comment by jandrieu** [comment]
@burnburn likes it. We'll close after we get an issue over there.

**Comment by kimdhamilton** [comment]
Ok to close
