### ISSUE TITLE
Update Scribe & Reintroduction List

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#39]
@kimdhamilton Can you update the Scribe & Reintroduction List to have only people that have been in meetings in the last few months, but keeping those that have volunteered recently at the end?

**Comment by kimdhamilton** [comment]
Updated, preserving most recent participants at the end of the list:
https://docs.google.com/document/d/1LkqZ10z7FeV3EgMIQEJ9achEYMzy1d_2S90Q_lQ0y8M/edit#

**Comment by kimdhamilton** [comment]
Need aliases!!

**Comment by kimdhamilton** [comment]
Aliases added. Quite a few people had multiple aliases, so I made my best guess. We can iterate
