### ISSUE TITLE
Complete update to Veres One DID Method spec

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#4]

**Comment by ChristopherA** [comment]
@msporny Many of us need this as the prototypical example of a DID method spec. What is status? What is blocking?

**Comment by ChristopherA** [comment]
We will bring this up at next CCG meeting in Action Item review (Dec 4th).

**Comment by kimdhamilton** [comment]
Can this be closed out? Does this suffice?
https://w3c-ccg.github.io/didm-veres-one/

**Comment by msporny** [comment]
> Can this be closed out? Does this suffice?

It doesn't suffice, we were trying to get to a fully complete all the way done DID Method spec... and we keep failing to prioritize it. It will be done eventually, but if you want to close the issue, that's fine... The issue being open isn't going to make it happen any faster... it is useful as a shaming method... did:shame:...

**Comment by kimdhamilton** [comment]
10/15: ok to close
