### ISSUE TITLE
Discussion group re: DID monetization models

### ISSUE THREAD

**Issue by mosesma** [w3c-ccg/community#40]
I'm pulling together a spinoff discussion about _DID monetization models_, which is likely going to be held on Thursday December 13th at noon PST. It'll be a Zoom conference, for 1 hour. Featuring Dr. Po Chi Wu. If you'd like to join, please up here ASAP: [https://goo.gl/forms/2tKbmbi5cDQMUBaC2 ](https://goo.gl/forms/2tKbmbi5cDQMUBaC2 )

Here's an initial list of possible business/revenue models: [https://docs.google.com/spreadsheets/d/1XyfIb3p80YlgcT-cbPe-bDsTkd1KvYbAYcIw7X_OmJk/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1XyfIb3p80YlgcT-cbPe-bDsTkd1KvYbAYcIw7X_OmJk/edit?usp=sharing)

**Comment by ChristopherA** [comment]
For now, lets move this to #RebootingWebOfTrust

**Comment by ChristopherA** [comment]
The members are welcome to resubmit as a possible work item for CCG later!
