### ISSUE TITLE
Update CCG Process

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#41]
* [x] Next draft of new CCG Process -- Friday Jan 24 (Joe)
* [x] Post for community review -- Tuesday Jan 28
* [ ] Conf call review -- Tuesday Feb 4
* [x] Start W3C Approval process (if any) -- Tuesday Feb 11
* [x] Update W3C Site -- Pending W3C Approval

We first talked about updating the larger CCG process on 2018-04-24. The transcript is at https://w3c-ccg.github.io/meetings/2018-04-24 and the google doc we referred then to is at https://docs.google.com/document/d/1vj811aUbs8GwZUNo-LIFBHafsz4rZTSnRtPv7RQaqNc/edit#heading=h.i2v9iagxg4em

In our meeting on 2018-09-18 we talked about the subset of the Work Item sub-portion of a CCG process. The transcript is at https://w3c-ccg.github.io/meetings/2018-09-18/ and the google doc we shared is at https://docs.google.com/document/d/1LeC0YNVMcAy_2MWrlKLw8i2WSxEaUEvUMxz8UdYC87U/edit#heading=h.ufzbq0sl8ef6

Other Links:

* Original CCG Process that needs revision: https://www.w3.org/community/about/agreements/
* W3C Community Group Process https://www.w3.org/community/about/agreements/#cgroups

**Comment by ChristopherA** [comment]
This action item is dependent on completing registries process https://github.com/w3c-ccg/community/issues/75

**Comment by kimdhamilton** [comment]
@jandrieu to invite Sumita to next week's meeting

**Comment by kimdhamilton** [comment]
we finished this; closing
