### ISSUE TITLE
look at security model or threat model of DIDs

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#43]
From @ChristopherA on 12/18 meeting:

look at security model (as opposed to just cryptographic) or threat model of DIDs

**Comment by kimdhamilton** [comment]
Note: no owner was identified, but Lionel and Ryan Grant may be able to help (per voice and IRC comments)

**Comment by jandrieu** [comment]
closing per editors. might be proposed again in the future.
