### ISSUE TITLE
Add Multihash as a work item

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/community#46]
The Multihash specification was drafted before/during the last RWoT and has been released as an IETF Internet-Draft. The specification is intended to be a joint work product of Protocol Labs (IPFS and Filecoin), the W3C Digital Verification Community Group, and the W3C Credentials Community Group.

https://lists.w3.org/Archives/Public/public-credentials/2019Jan/0005.html

Editors/Contributors: @jbenet @msporny @gannan08 @rhiaro

**Comment by kimdhamilton** [comment]
https://github.com/w3c-dvcg/multihash
