### ISSUE TITLE
Add Multibase as a work item

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/community#47]
The Multibase specification was just published a few days ago as an IETF Internet-Draft. The specification is intended to be a joint work product of Protocol Labs (IPFS and Filecoin), the W3C Digital Verification Community Group, and the W3C Credentials Community Group. Just as with Multihash, we need to decide if we're adopting it as a Work Item in the CCG.

https://lists.w3.org/Archives/Public/public-credentials/2019Jan/0006.html

Editors/Contributors: @jbenet @msporny @gannan08 @rhiaro

**Comment by kimdhamilton** [comment]
https://github.com/w3c-dvcg/multibase
