### ISSUE TITLE
Add Hashlink as a work item

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/community#48]
This issue is about the Hashlink specification, which is intended to be a way to enforce that the content at a given hyperlink has not changed since it was published. The specification is intended to be a joint work product of the W3C Digital Verification Community Group, JSON-LD WG (unofficial), VCWG (unofficial), and the W3C Credentials Community Group. The CCG needs to decide if it's adopting this specification as a Work Item.

https://lists.w3.org/Archives/Public/public-credentials/2019Jan/0010.html

Editors/Contributors: @msporny @gannan08 @kimdhamilton

**Comment by kimdhamilton** [comment]
https://github.com/w3c-dvcg/hashlink/
