### ISSUE TITLE
Discuss "DIDs, proof purposes, and verification methods" during CCG call

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#50]
Reference:
https://lists.w3.org/Archives/Public/public-credentials/2018Dec/0108.html

We need to ensure @dlongley can present on that day. (possibly tomorrow?)

His latest comments: 

> I think actionable items include updating the DID v1 JSON-LD context and
seeing if there are any references in the DID spec that need updating --
and updating the Linked Data Proof/Signature(s) specifications, which
are sorely in need of updating anyway.

**Comment by dlongley** [comment]
I can talk about the issue tomorrow (Jan 15).

**Comment by kimdhamilton** [comment]
Great, you're on the agenda

**Comment by kimdhamilton** [comment]
Discussed during 1/15 call
