### ISSUE TITLE
LD Key Format Registry administrivia

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#56]
- Needs repo
- Move from did spec repo [source](https://htmlpreview.github.io/?https://github.com/w3c-ccg/did-spec/blob/4eafb19e5c66b9d54e31d88460b89bdc00a07d80/ld-keys.html) to that repo

**Comment by kimdhamilton** [comment]
We need an LD cryptosuite registry. TODO: @msporny this is what we discussed on 2/5. I'm not sure I followed, but it sounds like we haven't started LD cryptosuites as a work item, and we'd like to. If so, I'll convert this into a request for volunteers to own this.

**Comment by msporny** [comment]
We currently have this registry: https://w3c-ccg.github.io/ld-cryptosuite-registry/

We need to extend that registry to also suggest key formats, which are naturally a part of each cryptosuite specification.

**Comment by ChristopherA** [comment]
What is required to close this?

**Comment by kimdhamilton** [comment]
only thing to do: add a section to registry that's also about key formats. Move to ld-cryptosuite-registry

**Comment by ChristopherA** [comment]
@dmitrizagidulin (or @manu & @talltree as DID editors) — you need to add the section as above so we can close this issue.

**Comment by dmitrizagidulin** [comment]
@kimdhamilton @ChristopherA Apologies, I'm not sure I fully follow. What do we need to do?

**Comment by rhiaro** [comment]
Paraphrasing manu on 2019-07-20 CCG call, what needs to be done is split the registry into Verification Methods and Key Formats and add some editorial stuff around it. Will put in a PR shortly.

**Comment by kimdhamilton** [comment]
To discuss on Nov 12 call: status check

cc @ChristopherA @jandrieu

**Comment by jandrieu** [comment]
This is done. Closing.
