### ISSUE TITLE
Updating ABNF for DIDs

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#57]
There are a variety of issues related to the ABNF of DIDs that is becoming critical path as new people from W3C and IETF communities join our meetings for DID discussions, and language and resolution and dereferencing. These issues cause problems for those who already have deep understanding of this area from other standards.

**Comment by talltree** [comment]
Christopher, I could not agree more. This is my #1 priority as a spec
editor. If we cover nothing else at Rebooting the Web of Trust next month
(March 1-3), I want to nail down the PRs around the ABNF.

I'm happy to discuss on this thread between now and then.

=Drummond

**Comment by jandrieu** [comment]
@dmitrizagidulin Created a PR to move this conversation forward https://github.com/w3c-ccg/did-spec/pull/168 

Please comment there.

We will also be discussing this on the next CCG call.

**Comment by peacekeeper** [comment]
I think this can be closed now that https://github.com/w3c-ccg/did-spec/pull/189 has been merged?

**Comment by kimdhamilton** [comment]
Closing per CCG call on July 2, 2019.
