### ISSUE TITLE
DID methods in the registry without associated DID specifications

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#59]
From @msporny 
I've been getting an increase in the number of requests for DID Method
registrations w/o provisional DID Method specs over the past couple of
months.

In many cases, the DID Methods that exist in the registry that don't
have associated specs were added by folks that noted that they would
provide a DID Method spec within a few days/weeks (and didn't follow
through). There are 5 such DID methods in the registry at present:

https://w3c-ccg.github.io/did-method-registry/

In hindsight, the PRs for those 5 DID Methods should never have been
approved.

If you have a DID Method registered in the registry and don't have an
associated DID specification, please add one now.

If these methods continue to not publish preliminary DID Method
specifications, the CCG will most likely need to consider removing them
from the registry.

**Comment by kimdhamilton** [comment]
chairs: check back in March 2019

**Comment by ChristopherA** [comment]
I know that a number of registrants have addressed their missing data. Which have not responded?

**Comment by kimdhamilton** [comment]
Created issues:

- https://github.com/w3c-ccg/did-method-registry/issues/29
- https://github.com/w3c-ccg/did-method-registry/issues/30
- https://github.com/w3c-ccg/did-method-registry/issues/31
- https://github.com/w3c-ccg/did-method-registry/issues/32

**Comment by ChristopherA** [comment]
@talltree , @msporny, @peacekeeper — let us know status and when we can close this.

**Comment by peacekeeper** [comment]
Updates from my perspective:
- I just sent the `did:dom` team an e-mail to point them to this issue, not sure what their status is.
- Glad to see a `did:jolo` method spec has been added by now.
- `did:uport` are active community participants, they must be aware of this, not sure when they are planning to write a method spec.
- Not sure who to contact from `dif:cnsnt`.

**Comment by kimdhamilton** [comment]
4/2 update: cnsnt is abandoned; uport is deprecated

**Comment by kimdhamilton** [comment]
propose to close

**Comment by kimdhamilton** [comment]
uPort is the only one remaining, but it's obsolete and we just need to figure out how to mark its status. 

That's tracked by https://github.com/w3c-ccg/did-method-registry/issues/31, so let's close this
