### ISSUE TITLE
CCG call connection problems

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#60]
Many people experiencing problems connecting to the CCG calls; discuss in future meeting?

**Comment by kimdhamilton** [comment]
4/2: seems to have cleared up

**Comment by msporny** [comment]
We have on boarded a number of people into our building, that are on our infrastructure, that don't understand that downloading 50GB files use a finite resource (bandwidth). We are in the process of:

* Tripling our incoming/outgoing bandwidth $$$
* Telling people to stop downloading kitten compilation videos :clubs: :clubs: :clubs: 

The connectivity issues w/ Twilio wrt. blocked robocall numbers went away, but given that they're using some advanced sentient AI to determine friend from foe (it's probably just a really complicated regex statement)... it may turn on @ChristopherA and @kimdhamilton again without warning. The AI seems to not like a select few numbers from the west coast... aside from that, we haven't been able to get anything else out of the sentient AI.

**Comment by kimdhamilton** [comment]
Let's keep an eye on it for now; seems better, but we can use mitigations Manu described above if problems flare up

**Comment by kimdhamilton** [comment]
Manu increased capacity; closing
