### ISSUE TITLE
Review results of 2018 EOY Survey 

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#61]
Review results of 2018 EOY Survey https://docs.google.com/document/d/1s15wHQEALSAQ3JUUScGGii3re2mJxGcQgIeSk1nHh5U/edit?usp=sharing

Heather Vescent is free on/after April 2 to present this. Ping Heather and Karn and when we lock down date.

**Comment by kimdhamilton** [comment]
@jandrieu @ChristopherA any objection to having this discussion 4/2? Heather and Karn would like 1 week notice, which means our usual Friday ahead is too late

**Comment by ChristopherA** [comment]
+1

**Comment by ChristopherA** [comment]
Scheduled for April 2nd, 2019 with @heathervescent

**Comment by kimdhamilton** [comment]
Completed
