### ISSUE TITLE
Need respec of RWOT paper as CCG Work Item

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#63]
We need a respec version of the RWOT paper on Data Minimization and Selective Disclosure, as a new work item for this group.

https://github.com/WebOfTrustInfo/rwot5-boston/blob/master/topics-and-advance-readings/Data-minimization-and-selective-disclosure.md

**Comment by ChristopherA** [comment]
This looks like it is complete at https://w3c-ccg.github.io/data-minimization/

Can we close?

**Comment by kimdhamilton** [comment]
This is done; closing
