### ISSUE TITLE
Review DID Charter PRs and Issues

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#66]
https://github.com/w3c-ccg/did-wg-charter

**Comment by kimdhamilton** [comment]
Kim will send email to CCG group re editorial issues; we can briefly discuss during action items

**Comment by kimdhamilton** [comment]
https://lists.w3.org/Archives/Public/public-credentials/2019May/0031.html

**Comment by jandrieu** [comment]
Done.
