### ISSUE TITLE
Book space at W3C TPAC 2019

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/community#67]
We should book space at W3C TPAC 2019 to report out on community stuff:

https://www.w3.org/2019/09/TPAC/

**Comment by kimdhamilton** [comment]
Ask at next meeting: is anyone going?

**Comment by kimdhamilton** [comment]
Note: Dan Burnett and Brent Zundel

**Comment by kimdhamilton** [comment]
Dan requested a space for DID WG, assuming one has been created

**Comment by ChristopherA** [comment]
The CCG is not booking space at this year's TPAC. If DID WG is chartered, they may meet. Closed.
