### ISSUE TITLE
Should we discuss roadmap on an ongoing basis during calls?

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#70]
something for us to discuss

**Comment by jandrieu** [comment]
What are thinking? Do you want to update the WBS? It's not clear we have a roadmap to discuss at this point. Although maybe that's the conversation: what's next after DIDs.

**Comment by ChristopherA** [comment]
May schedule roadmap talk after we know how DID WG will move topics and team out of CCG and who remains to do CCG work items?

**Comment by kimdhamilton** [comment]
closing; we need to rework this when we discuss planning for next year
