### ISSUE TITLE
[PROPOSED WORK ITEM] Verifiable Credentials Extension Registry

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/community#72]
# New Work Item Proposal

The Credentials CG currently curates a Verifiable Credential Status Registry, and will most likely curate other registries related to Verifiable Credentials. An issue was raised in the Verifiable Claims WG to consolidate all of the registries into a single document that lists
all the extensibility points that we know of in the spec. So the combined registry would contain all status schemes, terms of use schemes, proof mechanisms, evidence schemes, etc. That issue is here:

https://github.com/w3c/vc-data-model/issues/530

On April 30, 2019, the VCWG made the following resolution:

RESOLUTION: Issue #530 should be addressed by creating a Verifiable Credentials Extension Registry in the W3C Credentials Community Group and requesting that the registry is adopted as an official W3C CCG Work Item. Issue #530 should be closed after the W3C CCG accepts the registry as a Work Item.

This proposed work item puts the question of whether the Credentials Community Group wants to take the management of this informal registry on as an official work item.

## Link to Draft Pull Request

This PR creates the registry and adds initial content to it.

https://github.com/w3c-ccg/vc-extension-registry/pull/2

## Owners

Leads: Manu Sporny (@msporny), Dan Burnett (@burnburn), Justin Richer (@jricher), Jonathan Holt (@jonnycrunch)

**Comment by kimdhamilton** [comment]
To discuss 10/29:
I think this went through all the hoops. Ok to move forward?

**Comment by kimdhamilton** [comment]
@msporny did you already email the CCG alias about this? Sorry we were so slow to notice it

**Comment by msporny** [comment]
We covered this on a call: https://w3c-ccg.github.io/meetings/2019-07-02/#40

The PR was merged after multiple reviews... We're done here (and were done on July 2nd 2019). :)
