### ISSUE TITLE
Review DID wg charter issues

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#77]
Review during ongoing ccg calls

Need volunteers: https://github.com/w3c-ccg/did-wg-charter/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

**Comment by jandrieu** [comment]
Ok. I think we can close this. The charter has moved beyond the CCG.

Are you good with that, @kimdhamilton ?

**Comment by ChristopherA** [comment]
I say just close it. It has moved on ;-)
