### ISSUE TITLE
credentialSubject  of Verifiable Credentials Data Model 1.0

### ISSUE THREAD

**Issue by enuoCM** [w3c-ccg/community#78]
The definition of credentialSubject in [Verifiable Credentials Data Model 1.0](https://www.w3.org/TR/verifiable-claims-data-model/#credential-subject)

> The value of the credentialSubject property is defined as a set of objects that contain one or more properties that are each related to a subject of the verifiable credential. Each object MAY contain an id as described in Section § 4.2 Identifiers.

I don't quite understand this.  Is the credentialSubject a JSON object or a JSON array?

From this [example](https://www.w3.org/TR/verifiable-claims-data-model/#example-37-the-relationship-property-in-a-child-s-credential)
It seems that the **credentialSubject** merges the properties (ageUnder & parent) of **AgeCredential** and **RelationshipCredential** and is set as one JSON object.

I have four questions: 
1.  Dose it because that **AgeCredential** and **RelationshipCredential** in above example are about one [subject](https://www.w3.org/TR/verifiable-claims-data-model/#dfn-subjects), it then can be merged in one **credentialSubject** JSON object?
2.  If two different Credentials, such as **XXXCredential** and **YYYCredential**, both have a same associated property **ZZZ**, what should be the merged **credentialSubject**? 
3. Is there any **credentialSubject** example about two different [subject](https://www.w3.org/TR/verifiable-claims-data-model/#dfn-subjects)s?
4. Why not put the **Credential** type into the **credentialSubject**? Then the relation between subjects, properties and the credential types are more clear.

**Comment by TallTed** [comment]
This issue does not apply to the Credentials Community Group, and should instead be raised to the Verifiable Claims Working Group via the [issues page for the Data Model](https://github.com/w3c/vc-data-model/issues).

That said, I believe some if not all of your questions have been answered and/or addressed by revisions to the [Candidate Recommendation](https://www.w3.org/TR/verifiable-claims-data-model/#credential-subject), which you may see in the [current Editors Draft](https://w3c.github.io/vc-data-model/) (which does not explicitly say so, but is more recent than the published CR).

I suggest you start with the [revised definition](https://w3c.github.io/vc-data-model/#credential-subject) --

>A verifiable credential contains claims about one or more subjects. This specification defines a credentialSubject property for the expression of claims about one or more subjects.

-- and the [revised Example 37](https://w3c.github.io/vc-data-model/#example-37-a-relationship-credential-issued-to-a-parent).

**Comment by enuoCM** [comment]
@TallTed  Thanks for your information. I'll raise this issue to Verifiable Claims Working Group. BTW, the [revised definition](https://w3c.github.io/vc-data-model/#credential-subject) is in the CR version too and [revised Example 36](https://w3c.github.io/vc-data-model/#example-36-the-relationship-property-in-a-child-s-credential) is the original [Example 37](https://www.w3.org/TR/verifiable-claims-data-model/#example-37-the-relationship-property-in-a-child-s-credential).

**Comment by ChristopherA** [comment]
@enuoCM — did you raise this as issue in VCWG yet? Which issue, so we can close the issue here. Will close this issue next week if we don't hear from you.

**Comment by kimdhamilton** [comment]
closing
