### ISSUE TITLE
DID preparation for next TPAC

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#8]
- [ ] Chairs to ensure that work items are sticky and have the right company support
- [ ] Chairs to find people to produce DID use cases.
- [x] Chairs to find people to convert DID Primer to ReSpec format.
- [x] Chairs to find people to produce DID charter. Done: https://w3c-ccg.github.io/did-wg-charter/
- [x] Chairs to drum up W3C Member company support for DID WG.
- [ ] Chairs to find people to work on DID test suite.
- [ ] Production deployments

**Comment by msporny** [comment]
I've finished the DID WG Charter action item: https://w3c-ccg.github.io/did-wg-charter/

**Comment by jandrieu** [comment]
It's TIME!
