### ISSUE TITLE
Discuss "Nonviolent Communication for W3C Working Groups"

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#81]
Claire and Moses have worked on a paper called "Nonviolent Communication for W3C Working Groups". They'd like to discuss with the group. We can talk about potential next steps.

**Comment by kimdhamilton** [comment]
Moses requested to schedule this on 6/25

**Comment by kimdhamilton** [comment]
Chairs to ask Moses to share to list and discuss

**Comment by ChristopherA** [comment]
This was presented in Claire at a W3C call. Thanks for sharing! Closed.
