### ISSUE TITLE
Future meeting topic: chairs to schedule

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#82]
Future meeting topic from Heather Vescent:

> My company recently released two reports that may be of interest to this community.
> 
> 1: Entities, Identities, Registries: Exploring the Market Gaps in Corporate and IoT Identity: http://bit.ly/NPEreport
> This 32 page graphic heavy report, Entities, Identities, Registries, explains what Non-Person Entities are (NPEs), the relationships NPEs have with humans and each other, and identifies market gaps in today's technology solutions. This report identifies 11 market gaps - problems the private sector is not successfully/comprehensively solving to date.
> 
> 2: Security of Voter Data: http://bit.ly/vdsreport
> This research set out to understand the current state of voter rolls and the data that is collected, updated, stored, and accessed by various government entities. This 35 page graphic heavy report, Securing Voter Data Systems, explains the current state, identifies voter data vulnerabilities, and outlines an agenda for resilience.
> 
> This research was funded by DHS Science and Technology, Cybersecurity Directorate. I would be happy to go over these reports at a future CCG meeting if there is interest.

https://lists.w3.org/Archives/Public/public-credentials/2019Jun/0018.html

**Comment by kimdhamilton** [comment]
Per Heather: schedule after July 16

**Comment by jandrieu** [comment]
Before we schedule this, we'd like to see these reports available without signing up for a marketing list.

**Comment by TallTed** [comment]
Maybe this issue could be titled to indicate what the "future topic" is? (as there could be multiple such issues...)
