### ISSUE TITLE
Critical path problem with lack of JSON-LD 1.1 reference implementation

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#83]
For BTCR hackathon in August, we are not sure if there's a current (1.1) JSON-LD library we can use as a reference. We will need javascript and c, but we can port to c. Javascript implementation we can use that.

**Comment by TallTed** [comment]
[`jsonld.js`](https://github.com/digitalbazaar/jsonld.js), which powers the [JSON-LD Playground](https://json-ld.org/playground/), is probably the closest thing to a reference implementation.

**Comment by aljones15** [comment]
I believe the ruby implementation is actually the most up to date:

https://github.com/ruby-rdf/json-ld/

You can try both on the JSON-LD playground and see.

**Comment by peacekeeper** [comment]
I've been using https://github.com/jsonld-java/jsonld-java, which I think has partial support for JSON-LD 1.1, but doesn't support all of its features yet.

**Comment by ChristopherA** [comment]
One of the problems is a reference for both JSON-LD and signing. As far as I know only the old playground supports secp256k1 signing, but the signature block is way out of date, and @msporny said in the CCG call not expecting new release until late summer. But our BTCR hackathon is early August, and we want to do more F2F at #RWOT9. 

The risk here is that BTCR will use the JWT-based DIF signing code for BTCR and BTCR verifiable claims unless we have a working reference of current JSON-LD *AND* current secp256k1 signing.

**Comment by msporny** [comment]
We use jsonld.js for all of our internal and customer facing projects. It has everything that you'd need to support DIDs, VCs, LD Proofs, etc. 

If you want to sign stuff, there is vc-js, which can generate Ed25519 LD Proof digital signatures just fine and is conformant to the latest VC spec. It may not be a big lift to get secp256k1 signatures working, @dmitrizagidulin or @davidlehn would know more. 

We have also been experimenting w/ generating Windows, Mac OS X, and Linux binaries for normalizing, signing, etc... and will know more about those experiments in the next few weeks.

**Comment by msporny** [comment]
> The risk here is that BTCR will use the JWT-based DIF signing code for BTCR and BTCR verifiable claims unless we have a working reference of current JSON-LD AND current secp256k1 signing.

If you go down that path, make sure you understand the consequences:

https://w3c.github.io/vc-imp-guide/#benefits-of-json-ld-and-ld-proofs

**Comment by kimdhamilton** [comment]
this is being covered by Orie and other folks' writing
