### ISSUE TITLE
SIP not working

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#87]
I tried today from Europe to use Linphone on iOS and Mac, and both were unable to connect to sip:ccg@96.89.14.196. I've also tried OnSIP on iOS, which requires now an account from them. To date, I've not been able to get SIP working to get into our calls every time I've tried almost a year.

The iOS app reports that I'm connected as sip:christophera@sip.linphone.org so I don't think my AirBNB's ISP is blocking ports.

We need to verify that some combo of tools actually works (and not accept word from DB) and/or write better instructions for whatever is wrong, or remove this method as a way to access the CCG calls.

-- Christopher Allen

cc: @msporny @dlongley @kimdhamilton

**Comment by kimdhamilton** [comment]
@ChristopherA let’s ping for a volunteer to assign this to

**Comment by rhiaro** [comment]
I got onsip working in the browser today, so I can write that up

**Comment by David-Chadwick** [comment]
I just (re)installed onsip today on my new Mac and it worked a treat. 
Much better than the older version

David

**Comment by jandrieu** [comment]
FWIW, I have been able to get the SIP call-in working through OnSip on Windows 10. You have to hunt for the option to download & activate without creating an account, but it is possible. And it's worked reasonably well for me for maybe a year now.

**Comment by ChristopherA** [comment]
@rhiaro You said you'd write up some notes?

**Comment by ChristopherA** [comment]
I really would like to be able to use SIP on both iPhone and Mac when I'm in Buenos Aires before #RWOT10. 

@rhiaro — you said you had figured out how to get OnSip running on a laptop?

Could we get some help from folk to document how to do SIP on various platforms?

**Comment by jandrieu** [comment]
Let's iterate on this:  https://w3c-ccg.github.io/connecting.html

**Comment by ChristopherA** [comment]
We would like to have more SIP documentation to lower Digital Bazaar's costs in these call. Is anyone using any SIP clients other than Linphone? In particular, does anyone having SIP working on free iOS client?

Otherwise we should close this action item.

**Comment by jandrieu** [comment]
Yes, as mentioned previously, I have OnSip working on windows.

**Comment by msporny** [comment]
Just about everyone at our company has switched to OnSip and uses it from a variety of different platforms.

**Comment by kimdhamilton** [comment]
Propose closing this. I sense this will be obsolete when we finish jitsi migration, which is tracked here https://github.com/w3c-ccg/community/issues/126

**Comment by kimdhamilton** [comment]
Please re-open if there are any additional concerns.
