### ISSUE TITLE
Future meeting (Oct 1): how to support contribution to JSON-LD contexts and supporting documentation

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#88]
Raised by @OR13

Per https://github.com/w3c-ccg/did-spec/pull/270, let's discuss on October 1st how best to support contribution to JSON-LD Contexts and the supporting documentation.

As noted in the PR, there are a lot of documentation gaps, and it's not obvious how best to encourage contributors to help close them.

/cc @msporny

**Comment by kimdhamilton** [comment]
@msporny @OR13 would 10/15 be ok to discuss this?

**Comment by msporny** [comment]
> @msporny @OR13 would 10/15 be ok to discuss this?

Yep, confirming that both of us can make that time.

**Comment by OR13** [comment]
@dlongley can you cross link extending json-ld guidance here?

**Comment by kimdhamilton** [comment]
Coming back to this, do we need to file any issues against the LD working group?

**Comment by OR13** [comment]
I think we discussed on the call the best practice is to put some guidance in the did-core spec repo, and any other entry point where people may be introduced to JSON-LD.

I think this repo should also have its README updated, to include advice for how to contribute to evolving JSON-LD context and documentation:

https://github.com/w3c/vc-data-model/

I'm sure the LD WG probably has guidance on this, but for me, its critical that there be some friendly simply language explaining:

Should I attempt to update a context and documentation or host my own extensions?

What are the security implications of not providing a context, or not keeping it up to date, or not controlling its resolution?

Is it ok for me to use JSON-LD terms, but not actually support JSON-LD processing? (please no!)

We are not responsible for people not reading the docs, but we can provide some lighter eye catchers to encourage them to do so.... I think waving the security flag in their face is a good idea. 

Building on a technology without understanding it is inherently risky.

**Comment by David-Chadwick** [comment]
Hi Orie

if you are talking about the use of @context when creating VCs, then the 
guidance would be best added to the Implementation Guidelines, as this 
will be a common issue for every issuer that creates their own VCs. 
There is already some text in the Implementation Guidelines, but perhaps 
you would like more to be added

Kind regards

David

**Comment by kimdhamilton** [comment]
Discussed 5 Nov 2019. We should define/track action items for CCG and/or LD WG. This issue will be closed out next week

**Comment by OR13** [comment]
For reference: https://w3c.github.io/vc-imp-guide/

https://w3c.github.io/vc-imp-guide/#creating-new-credential-types

"We expect the most common extensions to the Verifiable Credentials Data Model to be new credential types. Whenever someone has something to say about one or more entities and they want their authorship to be verifiable, they should use a Verifiable Credential. Sometimes there may be an existing credential type, that someone else has created, that can be reused to make the statements they want to make. However, there are often cases where new credential types are needed.

New credential types can be created by following a few steps. This guide will also walk you through creating an example new credential type. At a high level, the steps to follow are:

Design the data model.
Create a new JSON-LD context.
Select a publishing location.
Use the new JSON-LD context when issuing new credentials."

This is good advice for credential implementers, however if the credential contains a JSON-LD Signature, there may be other contexts which the user has to update or extend, including the DID context.

The more time I spend with this stuff, the more I feel that the following is a best practice:

1. create your own contexts for everything you are doing.
2. don't rely on any contexts hosted anywhere you don't have control.

There are cases where you can't actually support 2, for example:

https://w3c.github.io/did-core/#example-6

```
{
  "@context": "https://www.w3.org/ns/did/v1"
}
```

"
DID method specifications MAY define their own JSON-LD contexts. However it is NOT RECOMMENDED to define a new context unless necessary to properly implement the method. Method-specific contexts MUST NOT override the terms defined in the generic DID context.
"

The issue is that the terms in any generic context are not under the control of an implementer, for example, supported key formats and signature algorithms used in the credential... so if you want your DID Method to support JOSE /JWK... what do you do? 

IMO, your only solution is to create your own context, and wait for the generic to maybe support your terms, and then remove them from your context.

**Comment by OR13** [comment]
@msporny I'm eager to close this issue out. I have a sorta long writeup on best practices for developers which I need to condense, before I can open a PR to add it to READMEs:

https://context.transmute.org/json-ld/

Any feedback welcome, I don't want this to be so long that its annoying, but I also want to ensure that developers can easily figure out how to fix things.

**Comment by kimdhamilton** [comment]
@OR13 I'd be glad to help with this. Would you like help reviewing? It actually doesn't look that long to me.

@msporny @OR13 @David-Chadwick just double-checking that I read the above correctly. Do we want this to end up in the VC implementation guidelines? If not, what alternatives are acceptable? Worst case I guess it can be a super-quick CCG note, or something along those lines

**Comment by msporny** [comment]
> https://context.transmute.org/json-ld/

Just read it... overall, I think the advice is good, but may start out with a use case that's a bit too complex. I do like the FAQ-like approach. Can we start with a simpler question? Like "I think I found a bug in a JSON-LD Context, where do I report it?" or "This JSON-LD Context I'm using doesn't have a property I need, how do I add it?" ... those are both "raise an issue and have someone else deal with it" responses... then we can move into "I want to fix it myself"... and that goes to raising a PR on the vocabulary and the context... all the way to self-hosting your own thing and then trying to get that adopted by the broader community.

**Comment by msporny** [comment]
> @msporny @OR13 @David-Chadwick just double-checking that I read the above correctly. Do we want this to end up in the VC implementation guidelines? If not, what alternatives are acceptable? Worst case I guess it can be a super-quick CCG note, or something along those lines

The discussion on the call today was to put it in any place that a person may be exposed to JSON-LD for the first time. So, README.md files in key locations that @OR13 has a better idea than me about.

**Comment by msporny** [comment]
The more I think about it, the more it sounds like @OR13 wants a CONTRIBUTING.md file that's pointed to by the README.md. "Want to make this steaming pile better? Read about how in CONTRIBUTING.md"

**Comment by OR13** [comment]
lol, yes, I think it probably does belong in CONTRIBUTING.md

I just want to make it super easy for other people to contribute to JSON-LD contexts, if its easy and friendly small PRs can save us all a lot of time.

I will try and refactor it around common contribution and cut it down a bit

**Comment by David-Chadwick** [comment]
I would favour something in the Implementation Guidelines, either full 
details of how to create your own @context when you want to add your own 
property to a VC, or a pointer to an external document where full 
details are given

Kind regards

David

**Comment by David-Chadwick** [comment]
I think the last two questions, with suitable edits, could ideally be 
placed in the Implementation Guidelines

kind regards

David

**Comment by OR13** [comment]
I have made some updates, and tried to split things up a bit so that they can be imported better:

https://github.com/transmute-industries/context/tree/master/json-ld

I will tackle a PR against the DID WG first.

**Comment by msporny** [comment]
> I have made some updates, and tried to split things up a bit so that they can be imported better

+1, read it, good set of revisions, looking forward to the DID WG PR. :)

**Comment by kimdhamilton** [comment]
@OR13 I read the guidelines and they are looking good. One thing I'm wondering is whether we should discuss backcompat. Specifically this line in "extending":

> Once your pull request is merged, you can use the updated context, and stop using your own hosted version.

I think that could break the signature values any credentials that used the previous context because the namespace would be different? I think it is true that one needs to maintain (versioned) any contexts for which credentials have been issued that need to remain verifiable.

**Comment by OR13** [comment]
yes, this is a good point... I think we need to add language about how changes in context can break signatures, and the responsibility of a credential issuer to scrutinize the context they include, and be certain that they will not disappear.

**Comment by kimdhamilton** [comment]
@msporny 
regarding @OR13's comment
>  scrutinize the context they include, and be certain that they will not disappear

Do we also want to recommend people use [perma-id](https://github.com/perma-id/w3id.org)?

It might be a good practice if people have doubts about whether it can be hosted long term. It looks like this repo is being steadily maintained

**Comment by kimdhamilton** [comment]
From CCG list, Gregg Kellogg's JSON-LD best practices: [https://w3c.github.io/json-ld-bp/](https://w3c.github.io/json-ld-bp/)

**Comment by kimdhamilton** [comment]
what remaining issues do we have before closing?

**Comment by OR13** [comment]
We need:

1. documentation for creating a new credential type with context and definitions in jsonld
2. documentation for extending the did core context with method specific parameters.

I have parts of both of these spread out, I just need to get over the anxiety and open a PR for the DID WG, and somewhere in the CCG VC Data Model.

**Comment by OR13** [comment]
To be referenced:

- Hosting contexts and json schema together: https://github.com/w3c-ccg/vc-json-schemas
- Greeting card Credential example: https://github.com/transmute-industries/vc-greeting-card
- DID WG conversations causing me to wait on my PR there.

**Comment by OR13** [comment]
I have compressed these to:  https://context.transmute.org/

Doing another round of copy edits, and then the plan is to open a PR with a link to this repo as "Transmute's perspective on contributing to JSON-LD", I don't think it's politically wise for this stuff to be framed another other way.

**Comment by kimdhamilton** [comment]
Let's discuss whether we can close during tomorrow's call

**Comment by kimdhamilton** [comment]
Also, do we feel we have the proper channels to document json-ld implementation considerations going forward? See [https://lists.w3.org/Archives/Public/public-credentials/2020Jan/0068.html](https://lists.w3.org/Archives/Public/public-credentials/2020Jan/0068.html)

**Comment by OR13** [comment]
Still pending DID WG settling.... Pending merging https://github.com/decentralized-identity/context into did core.

**Comment by kimdhamilton** [comment]
see #97

**Comment by kimdhamilton** [comment]
dupe of #97
