### ISSUE TITLE
Tracking of VC Maintenance Charter

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#90]
Do we need any accounting updates?

**Comment by kimdhamilton** [comment]
10/22 call: we should send call out to group giving 7-day heads up

- Dan, Manu, and any volunteers

**Comment by kimdhamilton** [comment]
Reference: http://htmlpreview.github.io/?https://github.com/msporny/charter-drafts/blob/msporny-vcwg-charter/verifiable-credentials-2019.html

**Comment by msporny** [comment]
PR under review by W3M, awaiting close of 7-day heads up for any objections: https://github.com/w3c/charter-drafts/pull/237#issuecomment-545090271

**Comment by kimdhamilton** [comment]
during oct 29 meeting, we can call final approval

**Comment by kimdhamilton** [comment]
this can be closed
