### ISSUE TITLE
Need a process summary for VCWG

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#94]
From 10/29 CCG call, we need a process summary for the maintenance mode VCWG and PR to W3C-CCG Home Page to refer to CCG work on VCs

- [https://w3c-ccg.github.io/meetings/2019-10-29/#action-2](https://w3c-ccg.github.io/meetings/2019-10-29/#action-2)
- [https://w3c-ccg.github.io/meetings/2019-10-29/#action-3](https://w3c-ccg.github.io/meetings/2019-10-29/#action-3)

**Relevant excerpt**

Dan Burnett: The proposal has both me (Dan Burnett) and Matt Stone to be the chairs. That can be modified as needed over time if we need another co-chair, etc.
Christopher Allen: I want to propose an item for you two... as far as creating a repo we can do that, just need a name from you. We also need a little bit about the process written down, we need that. Also on the W3C CCG website we need something about this work.
Christopher Allen: To tell people, "If you wish to comment or change things for VC data model spec, etc. you need to go here" The CCG chairs need help there, are you willing to accept that action item?
Manu Sporny: Agree that all of those are good ideas and are things that we need to do.

**Comment by kimdhamilton** [comment]
10 December: Dan and Manu started a conversation. Not just a conversation on WG, relates to CCG as well. Needs more discussion

**Comment by David-Chadwick** [comment]
Do we need to say something about the process for liaising with ISO SC17 WG10 mobile driving license working group.

**Comment by ChristopherA** [comment]
Final Vote January 9th.

**Comment by kimdhamilton** [comment]
@msporny @burnburn any updates on this?

**Comment by msporny** [comment]
Unfortunately, no... the VCWG process is not bumping up high enough in the priority queue based on all the other things going on. I have no ETA on when we'll get around to this given that both @burnburn and I are underwater and have been for some time. I suggest we try to find someone new that would be willing to take this on after a conversation w/ @msporny and @burnburn.

**Comment by kimdhamilton** [comment]
no updates to report

**Comment by msporny** [comment]
We met, got a process outlined, need to post it somewhere.

**Comment by msporny** [comment]
Rough outline is here: https://docs.google.com/document/d/1zpmxkY0mefzZf47GXNM0qC83lBEhyaRSBmf4NJpaa6M/edit

@burnburn may have fleshed it out more since we spoke last.

**Comment by kimdhamilton** [comment]
this outline is available for review: https://docs.google.com/document/d/1zpmxkY0mefzZf47GXNM0qC83lBEhyaRSBmf4NJpaa6M/edit

Dan encourages us all to review/comment

**Comment by kimdhamilton** [comment]
Per Heather: we'll discuss in 3 wks; aim to finish in 4 wks

**Comment by lrosenthol** [comment]
I left the specific comments on the GDoc - but I don't believe that most of the items on that list can be done under the current charter.  We need to get Ivan to check into it...

**Comment by vsnt** [comment]
We discussed this at July 28 CCG call (minutes: https://w3c-ccg.github.io/meetings/2020-07-28/) and there were no objections. 
1. Need to post the agreed process somewhere: https://docs.google.com/document/d/1zpmxkY0mefzZf47GXNM0qC83lBEhyaRSBmf4NJpaa6M/edit#
2. Then can close this item.

**Comment by vsnt** [comment]
Posted her: https://github.com/w3c-ccg/w3c-ccg.github.io/blob/master/VCWGmaintprocess.md and linked from main page: https://w3c-ccg.github.io/
