### ISSUE TITLE
VC chairs to send email about CCG to old VC-WG list, including asking for volunteers.

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#95]
From 10/29 CCG call, there was an action item for VC chairs to send email about CCG to old VC-WG list, including asking for volunteers.

[https://w3c-ccg.github.io/meetings/2019-10-29/#action-4](https://w3c-ccg.github.io/meetings/2019-10-29/#action-4)

**Comment by jandrieu** [comment]
Emails went out. Closing.
