### ISSUE TITLE
ACTION: merge the two crypto-ld registries, fix links

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/community#96]
From 10/29 meeting, there was an action item to "merge the two crypto-ld registries, fix links". See excerpt: [https://w3c-ccg.github.io/meetings/2019-10-29/#action-5](https://w3c-ccg.github.io/meetings/2019-10-29/#action-5)

*I don't understand what the specific action is here; assigning people involved in the conversation to help clarify. Also please assign the correct assignees*

**Comment by kimdhamilton** [comment]
To discuss on Nov 12 call: status check. Also see question above; not clear what the specific action item was

cc @ChristopherA @jandrieu

**Comment by kimdhamilton** [comment]
@ChristopherA we need to check status and/or clarify what this action item is. See my notes above

Note that we have assignees

**Comment by dmitrizagidulin** [comment]
@kimdhamilton The registries have been combined, this can be closed.
