### ISSUE TITLE
Need to host Schema for current JSON-LD Signatures

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#97]
There are a number of planned JSON-LD documents (that are not Verifiable Credentials) that plan to sign the documents with JSON-LD Signatures. These include some DIDs, revoked key lists, and other JSON-LD. However, there is no independent schema for JSON-LD Signatures. This schema could be subtracted from Verified Credentials scheme and should be be hosted somewhere in the CCG until a JSON-LD Signature WG takes it on toward a standard.

Ideally there should also be some functioning examples and pointers to reference code so that implementors can test their signing against the current specification.

This is also related to the task of archiving/closing out the DVCG in 2019 and moving any living specifications to new homes.

- [ ] Reliable URL people can start using to add to @context to support JSON-LD Signatures
- [ ] Test examples of various valid signed JSON-LD documents
- [ ] Links to various library and reference code (for instance I'd love to see JSON-LD signing playground updated to current standard)
- [ ] Update JSON-LD Signature spec in CCG, and move/archive https://github.com/w3c-dvcg/ld-signatures out

-- Christopher Allen

**Comment by ChristopherA** [comment]
- [ ] Prepare that these documents may move these to a new JSON-LD Signatures/Proofs WG if established.

**Comment by kimdhamilton** [comment]
what's the remaining work? ok to close?

**Comment by kimdhamilton** [comment]
Jan 14, 2020 Manu:

- there is a reference implementation
- there's a request for a context, which exists
- specs are out of date and need to be updated
- examples are out of date
- documentation isn't moving forward
- should have discussion on future call

**Comment by OR13** [comment]
@kimdhamilton @manu 

I have a proposal here:

https://github.com/digitalbazaar/jsonld-signatures/issues/82

^ this repo has the best jsonld implementation in javascript, but it relies on the soon to be deprecated https://www.npmjs.com/package/security-context

The sooner we mark the linked repo as deprecated / unsupported, the sooner we will get this stuff centralized under a new home.

**Comment by msporny** [comment]
> there is a reference implementation

https://github.com/digitalbazaar/jsonld-signatures

> there's a request for a context, which exists

https://w3id.org/security/v2

**Comment by msporny** [comment]
> The sooner we mark https://github.com/w3c-dvcg/security-vocab as deprecated / unsupported

Do not deprecate that, that is the reference vocabulary - Digital Bazaar uses it across all of our products and there is stuff in production now that depends on it. You will break things that will hurt us badly if you mark that repo as deprecated/unsupported. We do have releases out there, but that is THE source of truth for the security vocab.

The right thing to do there is to transfer the repo to the CCG - DO NOT deprecate - DO NOT mark it as unsupported.

**Comment by OR13** [comment]
@ChristopherA can you transfer "https://github.com/w3c-dvcg/security-vocab" to the ccg, I can help update the npm package once its moved. I won't be able to publish a new version to npm with the correct github links, however. 

Looking at the npm contributors for that module, it appears that anyone from digitalbazaar could.

**Comment by msporny** [comment]
> @ChristopherA can you transfer "https://github.com/w3c-dvcg/security-vocab" to the ccg

I just migrated the security-vocab to w3c-ccg. I'll ask @davidlehn to republish the npm package when he gets in today.

**Comment by msporny** [comment]
@OR13 wrote:
> I won't be able to publish a new version to npm with the correct github links, however.

If you'd like publish/edit privileges, @OR13, just let us know, happy to give them to you.

**Comment by OR13** [comment]
@msporny I hope we are not needing to make changes that frequently, I think the more likely scenario will be that we will need to make a lot of documentation updates to get all the context properties defined and hosted somewhere, that should be mostly a github / PR issue.

Excited we got this bit moved the CCG! Thank you!.

**Comment by msporny** [comment]
This discussion is very active now... There are four JSON-LD Contexts that we need to be aware of: the the VC context, the DID context, the DIF context, and the Linked Data Security context. We need to figure out how all of those work together and a plan of how people use contexts in each of those scenarios.

Next step is having a CCG meeting that is not a part of the main call to come up with a plan.

**Comment by kimdhamilton** [comment]
TODO: schedule a future public meeting (outside of regular meetings) with this topic.

We need these at CCG:
- VC schema
- LD security context

**Comment by davidlehn** [comment]
FYI, the security vocab/context moved.  There's an open PR to move the w3id redirect over to the ccg repos: https://github.com/perma-id/w3id.org/pull/1638. If there's further discussion on this topic that change could wait.

**Comment by OR13** [comment]
This is semi-blocking: https://github.com/w3c/did-core-registry/issues/3

We can't / won't point to vocabulary that does not exist / cannot be easily updated by W3C WG members.

**Comment by kimdhamilton** [comment]
the blocked issue above (w3c/did-spec-registries#3) has been resolved but I believe this issue will still arise in other contexts

**Comment by kimdhamilton** [comment]
from @OR13: this and #88 may not be resolvable without a working group. Proposal to address by ensuring editors of CCG specs that use JSON-LD are listed as contacts to help resolve JSON-LD issues.

**Comment by OR13** [comment]
I would say... we are responsible for this... and we are improving slowly: https://github.com/w3c-ccg/security-vocab

**Comment by kimdhamilton** [comment]
Discussion from 8/4:
- Gather CCG work items related to json-ld, find editors, and funnel ppl to them. Perhaps this will force documentation
- Chairs can curate and publish
- Invite external review

**Comment by jonnycrunch** [comment]
https://github.com/w3c/did-spec-registries/issues/79

**Comment by vsnt** [comment]
Add a new page to the CCG site to document the JSON-LD experts in case of questions. The experts on this page are Manu and Dave Longley at Digital Bazaar as part of the W3C JSON-LD group.

Still to do: figure out where to host this on the CCG page and actually make it.

**Comment by OR13** [comment]
@vsnt please include ALL CODEOWNERS in any ccg repo that supports JSON-LD in that list, and maybe the list of repos as well... off the top of my head, they are:

- https://github.com/w3c-ccg/security-vocab
- https://github.com/w3c-ccg/did-method-key
- https://github.com/w3c-ccg/lds-jws2020
- https://github.com/w3c-ccg/lds-ecdsa-secp256k1-2019
- https://github.com/w3c-ccg/did-method-web
- https://github.com/w3c-ccg/ldp-bbs2020
- https://github.com/w3c-ccg/vc-http-api
- https://github.com/w3c-ccg/did-resolution
- https://github.com/w3c-ccg/vc-examples
- https://github.com/w3c-ccg/vp-request-spec
- https://github.com/w3c-ccg/zcap-ld
- https://github.com/w3c-ccg/webkms
- https://github.com/w3c-ccg/ld-cryptosuite-registry
- https://github.com/w3c-ccg/universal-wallet-interop-spec
- https://github.com/w3c-ccg/ld-proofs
- https://github.com/w3c-ccg/did-method-v1

We have a lot of people in this community who could support JSON-LD better, by relying on Digital Bazaar for everything JSON-LD we are risking creating an environment of learned helplessness :)

The more often someone a little less sure of themselves can solve a problem for the community, the stronger the support network grows.

**Comment by vsnt** [comment]
@OR13 thanks for that list. @msporny and @dlongley were mentioned in our CCG chair mtg because I'm trying to get completion on these longstanding open items. 

1. Who are other folks we should include in this list?
2. What other information/repos/examples/etc should be referenced?
3. Where would be the ideal place to put this resource? On ccg-github.io? on the CCG W3C Blog? Somewhere else? (There are a lot of rando pages that are difficult to know are there unless you live and breathe in this community and this set of resources are for people who do not.)

**Comment by msporny** [comment]
+1 for getting Digital Bazaar out of the critical path.

> Who are other folks we should include in this list (of JSON-LD Experts)?

Orie (@OR13), Tobias (@tplooker), Ivan Herman (@iherman) -- adjacent to this community -- Rob (@azaroth42), Benjamin (@bigbluehat), Gregg Kellogg (@gkellogg).

**Comment by OR13** [comment]
IMO, it should be top of repo README's and probably at the top of welcome to the CCG web page, given how much linked data stuff we are responsible for.

**Comment by wyc** [comment]
One possible destination for managing static links such as w3id.org is the infrastructure task force, which is pending chair approval: https://github.com/w3c-ccg/community/issues/168

**Comment by wyc** [comment]
Orie (@OR13), Tobias (@tplooker), Ivan Herman (@iherman) -- adjacent to this community -- Rob (@azaroth42), Benjamin (@BigBlueHat), Gregg Kellogg (@gkellogg).

Would you be willing willing to come to a prospective Infrastructure Task Force meeting in January (pending #168) to arrive to a final conclusion of where this lives and how it's governed? Please emoji like this comment if so.

**Comment by gkellogg** [comment]
@wyc Sure, I can come to such aa meeting.

**Comment by azaroth42** [comment]
I'm happy to, but not certain that I'm needed. Don't schedule around me :)

**Comment by wyc** [comment]
Tracking this issue in the ITF: https://github.com/w3c-ccg/infrastructure/issues/10

I've included relevant excerpts from this thread to help us address this issue. Thanks everyone.
