### ISSUE TITLE
[PROPOSED WORK ITEM] did:key DID Method

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/community#98]
## Abstract and Draft 

Decentralized Identifiers (DIDs) are a new type of identifier for verifiable, decentralized digital identity. These new identifiers are designed to enable the controller of a DID to prove control over it and to be implemented independently of any centralized registry, identity provider, or certificate authority. These sorts of identifiers often utilize a heavy-weight registry, such as ones utilizing Decentralized Ledger Technologies (DLT), to create, read, update, and deactivate DIDs. This specification describes a non-registry based DID Method based on expanding a cryptographic public key into a DID Document. This approach provides the simplest possible implementation of a DID Method that is able to achive many, but not all, of the benefits of utilizing DIDs.

https://digitalbazaar.github.io/did-method-key/

## List Owners

Current Editors: @msporny, @dlongley, @dmitrizagidulin

**Comment by David-Chadwick** [comment]
I am proposing to use this DID in my VC implementation, so I am happy to work on the spec with you. Question I have are as follows:
1. Why use base58 and not base64. The ID is not meant to be human consumable to confusion between 0 and O should not be an issue. We are already using base64 for our keys using the JWT spec. So I would like us to move to base64 encoding
2. Is there (going to be) a published table somewhere for the public key types that precede the key, or is this left up to the implementors to choose

**Comment by kimdhamilton** [comment]
@ChristopherA: @msporny has 2 proposed work items. One of them is the main topic. For the other we can give him some time to give a brief introduction during the action items 

We may in fact have extra time during the meeting, in which case he can present both for the main agenda

**Comment by kimdhamilton** [comment]
approved. I'll kick off the next steps

**Comment by kimdhamilton** [comment]
finished: https://github.com/w3c-ccg/did-method-key
