### ISSUE TITLE
[PROPOSED WORK ITEM] WebKMS

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/community#99]
## Abstract and Draft 

Cryptographic authentication systems enable machines, individuals, and organizations to more securely interact with one another. These systems often use public-private key cryptography or encryption mechanisms in order to manage cryptographic material as well as operations utilizing that material. This specification provides a common data model and interface for interacting with these systems enabling one to perform secure cryptographic operations such as keypair creation, wrapping and unwrapping, signing, encrypting, and decrypting.

https://digitalbazaar.github.io/webkms/

## Owners

Current editors: @msporny, @dlongley

**Comment by awoie** [comment]
How does the spec relate to the work of the Cloud Signature Consortium: https://cloudsignatureconsortium.org/resources/ ?

**Comment by msporny** [comment]
> How does the spec relate to the work of the Cloud Signature Consortium: https://cloudsignatureconsortium.org/resources/ ?

I made an attempt at an answer here - https://lists.w3.org/Archives/Public/public-credentials/2019Nov/0093.html

**Comment by kimdhamilton** [comment]
@ChristopherA: @msporny has 2 proposed work items. One of them is the main topic. For the other we can give him some time to give a brief introduction during the action items 

We may in fact have extra time during the meeting, in which case he can present both for the main agenda

**Comment by kimdhamilton** [comment]
10 December: make this a topic of a call so people can rapid fire questions.

**Comment by kimdhamilton** [comment]
finished: https://github.com/w3c-ccg/webkms
